### ISSUE TITLE
Mention `gradient`  in the _Getting started_ section

### ISSUE THREAD

**Issue by scheidan** [EnzymeAD/Enzyme.jl#1035]
Currently the user-friendly function `gradient` and it's friends are only mentioned in the API section.

I think it would be great for new users to have it in the Readme and in the _Getting started_ section. 

This more in line with other AD packages 
```Julia
gradient(Reverse, rosenbrock, [1.0, 2.0])
```
and seems much simpler than
```Julia
autodiff(Reverse, rosenbrock, Active, Active(1.0), Active(2.0))
```

In case  `gradient` has a lower performance than `autodiff`, the _Getting started_ section would be a good place to explain this too.

**Comment by wsmoses** [comment]
Sure, contributions welcome!
