### ISSUE TITLE
`CombinedAdjointThunk` should also return ret value

### ISSUE THREAD

**Issue by vchuravy** [EnzymeAD/Enzyme.jl#107]
```
julia> autodiff(f, Active(2.0))
(4.0,)
```

Should maybe be:
```
julia> (4.0, (4.0,))
(4.0, (4.0,))
```

**Comment by vchuravy** [comment]
https://github.com/wsmoses/Enzyme.jl/blob/aa78016bfd046689aa33b2ceba50049b329dd0d5/src/compiler.jl#L1189

**Comment by vchuravy** [comment]
@tansongchen this might be a good place to start.

**Comment by tansongchen** [comment]
Just went though compiler.jl, this should be straightfoward. will do it

**Comment by wsmoses** [comment]
Adding this as an option actually enables us to handle https://github.com/wsmoses/Enzyme.jl/issues/112 by simply returning the shadow return via the corresponding shadow return arg.

**Comment by vchuravy** [comment]
@wsmoses #537 did implement this right?

**Comment by wsmoses** [comment]
I don't think so, but it changed the ABI to have a place for this.

**Comment by wsmoses** [comment]
Done in https://github.com/EnzymeAD/Enzyme.jl/pull/598
