### ISSUE TITLE
Forward mode of an ODE solver fails with TypeAnalysisDepthLimit

### ISSUE THREAD

**Issue by ChrisRackauckas** [EnzymeAD/Enzyme.jl#1070]
MWE:

```julia
using OrdinaryDiffEq, Enzyme, ForwardDiff
Enzyme.API.runtimeActivity!(true)

function f(u0p)
	prob = ODEProblem((u, p, t) -> u .* p, u0p[1:1], (0.0, 1.0), u0p[2:2])
    Array(solve(prob, Tsit5(), abstol = 1e-12, reltol = 1e-12, saveat = 0.1))
end
u0p = [2.0, 3.0]
jac1 = Enzyme.jacobian(Forward, f, u0p)
```

Output of the run is attached:

[output.txt](https://github.com/EnzymeAD/Enzyme.jl/files/12707023/output.txt)

**Comment by ChrisRackauckas** [comment]
Simpler version:

```julia
using SimpleDiffEq, Enzyme, ForwardDiff, StaticArrays
Enzyme.API.runtimeActivity!(true)

function f(u0p)
	prob = ODEProblem((u, p, t) -> u .* p, SVector{1}(u0p[1:1]), (0.0, 1.0), u0p[2:2])
    Array(solve(prob, SimpleATsit5(), abstol = 1e-12, reltol = 1e-12, saveat = 0.1))
end
u0p = [2.0, 3.0]
jac1 = Enzyme.jacobian(Forward, f, u0p)
jac2 = ForwardDiff.jacobian(f, u0p)

jac1 ≈ jac2
```

and the simplest:

```julia
using SimpleDiffEq, Enzyme, ForwardDiff, StaticArrays
Enzyme.API.runtimeActivity!(true)

function f(u0p)
	prob = ODEProblem((u, p, t) -> u .* p, SVector{1}(u0p[1:1]), (0.0, 1.0), u0p[2:2])
    Array(solve(prob, GPUSimpleATsit5(), abstol = 1e-12, reltol = 1e-12, saveat = 0.1))
end
u0p = [2.0, 3.0]
jac1 = Enzyme.jacobian(Forward, f, u0p)
jac2 = ForwardDiff.jacobian(f, u0p)

jac1 ≈ jac2
```

This last one is just a loop:

https://github.com/SciML/SimpleDiffEq.jl/blob/master/src/tsit5/gpuatsit5.jl#L99-L223

so it's surprising that one fails with Forward mode. It fails with: [output2.txt](https://github.com/EnzymeAD/Enzyme.jl/files/12707030/output2.txt)

**Comment by wsmoses** [comment]
We didn't add the forward mode rule to the solver, which is the correct solution here.

Presumably reopen this issue on DiffEqBase.jl?

**Comment by wsmoses** [comment]
Oh and the precise issue from the log is equivalent to: https://github.com/EnzymeAD/Enzyme.jl/issues/274

**Comment by ChrisRackauckas** [comment]
> We didn't add the forward mode rule to the solver, which is the correct solution here.

We do want to support Enzyme directly on the solvers in the future though, since it is mathematically different from the adjoint rule over the solver. This is the difference of continuous and discrete adjoints, summarized in https://arxiv.org/abs/2001.04385:

> Previous research has shown that the discrete adjoint approach is more stable
than continuous adjoints in some cases [53, 47, 94, 95, 96, 97] while continuous
36 adjoints have been demonstrated to be more stable in others [98, 95] and can
reduce spurious oscillations [99, 100, 101]. This trade-off between discrete and
continuous adjoint approaches has been demonstrated on some equations as
a trade-off between stability and computational efficiency [102, 103, 104, 105,
106, 107, 108, 109, 110]. Care has to be taken as the stability of an adjoint
approach can be dependent on the chosen discretization method [111, 112, 113,
114, 115], and our software contribution helps researchers switch between all
of these optimization approaches in combination with hundreds of differential
equation solver methods with a single line of code change.

Given the improved stability, we would like to try Enzyme on that against the adjoint overloads sometime. Currently the best benchmarks we have are from this paper: https://ieeexplore.ieee.org/abstract/document/9622796 or arxiv https://arxiv.org/abs/1812.01892. From this we see two things:

First is that direct forward mode of the solver (DSAAD) is just faster than the forward rules. The reason is because you can fuse computations from the primal better into the derivative ODEs.

![Screenshot 2023-09-24 092827](https://github.com/EnzymeAD/Enzyme.jl/assets/1814174/9522e2bb-b93e-47ef-b688-f2e9861f4c68)

The second is that the adjoints do faster in reverse, but part of that may be due to implementation.

![Screenshot 2023-09-24 092945](https://github.com/EnzymeAD/Enzyme.jl/assets/1814174/054e050e-eaa3-4f9d-b97d-cf21f365e896)

We want to revisit this all now with Enzyme.
