### ISSUE TITLE
`sum` wrong gradient on Julia 1.10-nightly

### ISSUE THREAD

**Issue by jgreener64** [EnzymeAD/Enzyme.jl#1119]
On Enzyme main (b635408695e358e5798297e474bd768dec0ef4da) and Julia 1.10-nightly this gives the wrong gradient:
```julia
using Enzyme
f(x) = sum(diff([0.0 x; 1.0 2x]; dims=2))
autodiff(Reverse, f, Active, Active(2.0))[1][1]
```
```
1.0 # Should be 3.0
```
See the CI logs at https://github.com/EnzymeAD/Enzyme.jl/actions/runs/6678494431/job/18149594449?pr=969.

**Comment by wsmoses** [comment]
This no longer reproduces for me on main, please reopen if it persists [and I suppose rebase that PR?]

**Comment by jgreener64** [comment]
On CI on Julia 1.10-nightly this seems to be throwing a `StackOverflowError`: https://github.com/EnzymeAD/Enzyme.jl/actions/runs/6797095128/job/18478504650?pr=969.

Also for the following:
```julia
using Enzyme
f(x) = rot180([x 2x; 3x 4x], 3)[1, 1]
autodiff(Reverse, f, Active, Active(2.0))[1][1] # Should be 4.0
```

**Comment by wsmoses** [comment]
yeah 1.10 broke upstream recently, a seprarate issue was opened for that: https://github.com/EnzymeAD/Enzyme.jl/issues/1134
