### ISSUE TITLE
Custom rule not selected despite generic function signature

### ISSUE THREAD

**Issue by lassepe** [EnzymeAD/Enzyme.jl#1178]
I'm running into settings where my reverse rule never gets selected despite having a generic signature that should match all methods of my function.

Below is an MWE:

```julia
using Enzyme
using Random

function foo(tensors)
    x = randn(100)
    y = randn(100)

    (; x, y)
end

function bar(tensors)
    sum(foo(tensors).x)
end

# catch-all augmented_primal that should always be hit for foo
function EnzymeRules.augmented_primal(config, func::Enzyme.Annotation{typeof(foo)}, args...)
    println("my augmented primal with args: $args")

    EnzymeRules.AugmentedReturn(nothing, nothing, nothing)
end

# catch-all reverse rule that should always be hit for foo
function EnzymeRules.reverse(config, func::Enzyme.Const{typeof(foo)}, args...)
    println("my reverse with args: $args")

    (nothing,)
end

A = [1.0 2.0; 3.0 4.0]
B = -A

x = [A, B]
dx = [zero(A), zero(B)]

autodiff(Reverse, bar, Active, Duplicated(x, dx))
dx
```

Instead of using my custom rule, Enzyme tries do diff through `foo` and errors out on the `randn` call with

```julia
ERROR: LoadError: AssertionError: value_type(v) == nty
```

<details>
<summary>Click to expand stacktrace</summary>

```julia
ERROR: task switch not allowed from inside staged nor pure functions
Stacktrace:
  [1] try_yieldto(undo::typeof(Base.ensure_rescheduled))
    @ Base ./task.jl:921
  [2] wait()
    @ Base ./task.jl:995
  [3] uv_write(s::Base.TTY, p::Ptr{UInt8}, n::UInt64)
    @ Base ./stream.jl:1048
  [4] unsafe_write(s::Base.TTY, p::Ptr{UInt8}, n::UInt64)
    @ Base ./stream.jl:1120
  [5] write
    @ Base ./strings/io.jl:248 [inlined]
  [6] print
    @ Base ./strings/io.jl:250 [inlined]
  [7] print(::Base.TTY, ::String, ::String, ::Vararg{String})
    @ Base ./strings/io.jl:46
  [8] println(::Base.TTY, ::String, ::Vararg{String})
    @ Base ./strings/io.jl:75
  [9] println(xs::String)
    @ Base ./coreio.jl:4
 [10] nodecayed_phis!(mod::LLVM.Module)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/rbuCz/src/compiler/optimize.jl:205
 [11] optimize!
    @ ~/.julia/packages/Enzyme/rbuCz/src/compiler/optimize.jl:1137 [inlined]
 [12] codegen(output::Symbol, job::GPUCompiler.CompilerJob{…}; libraries::Bool, deferred_codegen::Bool, optimize::Bool, toplevel::Bool, strip::Bool, validate::Bool, only_entry::Bool, parent_job::Nothing)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/rbuCz/src/compiler.jl:9262
 [13] codegen
    @ ~/.julia/packages/Enzyme/rbuCz/src/compiler.jl:8886 [inlined]
 [14] _thunk(job::GPUCompiler.CompilerJob{Enzyme.Compiler.EnzymeTarget, Enzyme.Compiler.EnzymeCompilerParams}, postopt::Bool) (repeats 2 times)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/rbuCz/src/compiler.jl:9830
 [15] cached_compilation
    @ ~/.julia/packages/Enzyme/rbuCz/src/compiler.jl:9864 [inlined]
 [16] (::Enzyme.Compiler.var"#474#475"{…})(ctx::LLVM.Context)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/rbuCz/src/compiler.jl:9921
 [17] JuliaContext(f::Enzyme.Compiler.var"#474#475"{…})
    @ GPUCompiler ~/.julia/packages/GPUCompiler/U36Ed/src/driver.jl:47
 [18] #s325#473
    @ ~/.julia/packages/Enzyme/rbuCz/src/compiler.jl:9882 [inlined]
 [19] 
    @ Enzyme.Compiler ./none:0
 [20] (::Core.GeneratedFunctionStub)(::UInt64, ::LineNumberNode, ::Any, ::Vararg{Any})
    @ Core ./boot.jl:600
 [21] autodiff(::ReverseMode{false, FFIABI}, f::Const{var"#1#2"}, ::Type{Active}, args::Duplicated{Vector{Matrix{Float64}}})
    @ Enzyme ~/.julia/packages/Enzyme/rbuCz/src/Enzyme.jl:207
 [22] autodiff(::ReverseMode{false, FFIABI}, ::var"#1#2", ::Type, ::Duplicated{Vector{Matrix{Float64}}})
    @ Enzyme ~/.julia/packages/Enzyme/rbuCz/src/Enzyme.jl:222
 [23] top-level scope
    @ REPL[1]:8
 [24] top-level scope
    @ ~/.julia/packages/Infiltrator/LtFao/src/Infiltrator.jl:726
Some type information was truncated. Use `show(err)` to see complete types.
```

</details>

# Version Info

Happens both on julia 1.10.0-rc1 and 1.9.4.
Happens both on enzyme 0.11.10 and main (41c78adb886df5623f42fcc8a552fccaba12560c).

Note that on main I don't hit the exact same assert but a slightly different error:

<details>
<summary> Click to expand error for 41c78adb886df5623f42fcc8a552fccaba12560c </summary>

ERROR: LoadError: Enzyme compilation failed.
Current scope: 
define internal fastcc void @julia_randn__3272({} addrspace(10)* noundef nonnull align 16 dereferenceable(40) %0) unnamed_addr #42 !dbg !1330 {
top:
  %newstruct = alloca [2 x i64], align 8
  %1 = alloca [2 x i64], align 8
  %2 = call {}*** @julia.get_pgcstack()
  %ptls_field52 = getelementptr inbounds {}**, {}*** %2, i64 2
  %3 = bitcast {}*** %ptls_field52 to i64***
  %ptls_load5354 = load i64**, i64*** %3, align 8, !tbaa !38
  %4 = getelementptr inbounds i64*, i64** %ptls_load5354, i64 2
  %safepoint = load i64*, i64** %4, align 8, !tbaa !42, !invariant.load !37
  fence syncscope("singlethread") seq_cst
  call void @julia.safepoint(i64* %safepoint), !dbg !1331
  fence syncscope("singlethread") seq_cst
  %5 = bitcast {} addrspace(10)* %0 to { i8 addrspace(13)*, i64, i16, i16, i32 } addrspace(10)*, !dbg !1332
  %6 = addrspacecast { i8 addrspace(13)*, i64, i16, i16, i32 } addrspace(10)* %5 to { i8 addrspace(13)*, i64, i16, i16, i32 } addrspace(11)*, !dbg !1332
  %arraylen_ptr = getelementptr inbounds { i8 addrspace(13)*, i64, i16, i16, i32 }, { i8 addrspace(13)*, i64, i16, i16, i32 } addrspace(11)* %6, i64 0, i32 1, !dbg !1332
  %arraylen = load i64, i64 addrspace(11)* %arraylen_ptr, align 8, !dbg !1332, !tbaa !162, !range !165, !alias.scope !166, !noalias !167
  %7 = icmp ugt i64 %arraylen, 6, !dbg !1335
  br i1 %7, label %L32, label %L4, !dbg !1334

L4:                                               ; preds = %top
  %.not = icmp eq i64 %arraylen, 0, !dbg !1337
  br i1 %.not, label %L108, label %L16.preheader, !dbg !1344

L16.preheader:                                    ; preds = %L4
  %8 = bitcast {} addrspace(10)* %0 to double addrspace(13)* addrspace(10)*
  %9 = addrspacecast double addrspace(13)* addrspace(10)* %8 to double addrspace(13)* addrspace(11)*
  br label %L16, !dbg !1345

L16:                                              ; preds = %L16, %L16.preheader
  %value_phi6 = phi i64 [ %13, %L16 ], [ 1, %L16.preheader ]
  %10 = call double @julia_randn_3357(), !dbg !1346
  %11 = add nsw i64 %value_phi6, -1, !dbg !1347
  %arrayptr55 = load double addrspace(13)*, double addrspace(13)* addrspace(11)* %9, align 16, !dbg !1347, !tbaa !172, !alias.scope !1349, !noalias !167, !nonnull !37
  %12 = getelementptr inbounds double, double addrspace(13)* %arrayptr55, i64 %11, !dbg !1347
  store double %10, double addrspace(13)* %12, align 8, !dbg !1347, !tbaa !175, !alias.scope !178, !noalias !1352
  %.not56 = icmp eq i64 %value_phi6, %arraylen, !dbg !1353
  %13 = add nuw nsw i64 %value_phi6, 1, !dbg !1355
  br i1 %.not56, label %L108, label %L16, !dbg !1345

L32:                                              ; preds = %top
  %14 = addrspacecast {} addrspace(10)* %0 to {} addrspace(11)*, !dbg !1332
  %15 = call token (...) @llvm.julia.gc_preserve_begin({} addrspace(10)* nonnull %0), !dbg !1356
  %16 = call nonnull {}* @julia.pointer_from_objref({} addrspace(11)* noundef %14) #43, !dbg !1357
  %17 = bitcast {}* %16 to i8**, !dbg !1357
  %arrayptr12 = load i8*, i8** %17, align 8, !dbg !1357, !tbaa !172, !alias.scope !166, !noalias !167, !nonnull !37
  %18 = ptrtoint i8* %arrayptr12 to i64, !dbg !1357
  %19 = getelementptr inbounds [2 x i64], [2 x i64]* %newstruct, i64 0, i64 0, !dbg !1361
  store i64 %18, i64* %19, align 8, !dbg !1361, !tbaa !126, !alias.scope !128, !noalias !1363
  %20 = getelementptr inbounds [2 x i64], [2 x i64]* %newstruct, i64 0, i64 1, !dbg !1361
  store i64 %arraylen, i64* %20, align 8, !dbg !1361, !tbaa !126, !alias.scope !128, !noalias !1363
  %21 = addrspacecast [2 x i64]* %newstruct to [2 x i64] addrspace(11)*, !dbg !1356
  call void @julia_rand__3328([2 x i64]* noalias nocapture nofree noundef nonnull writeonly sret([2 x i64]) align 8 dereferenceable(16) %1, [2 x i64] addrspace(11)* nocapture nofree noundef nonnull readonly align 8 dereferenceable(16) %21), !dbg !1356
  call void @llvm.julia.gc_preserve_end(token %15), !dbg !1356
  %arraylen16 = load i64, i64 addrspace(11)* %arraylen_ptr, align 8, !dbg !1364, !tbaa !162, !range !165, !alias.scope !166, !noalias !167
  %.not57 = icmp eq i64 %arraylen16, 0, !dbg !1373
  br i1 %.not57, label %L108, label %L32.L51_crit_edge, !dbg !1372

L32.L51_crit_edge:                                ; preds = %L32
  %22 = bitcast {} addrspace(10)* %0 to i8 addrspace(13)* addrspace(10)*
  %arrayptr_ptr23.phi.trans.insert = addrspacecast i8 addrspace(13)* addrspace(10)* %22 to i8 addrspace(13)* addrspace(11)*
  %arrayptr24.pre = load i8 addrspace(13)*, i8 addrspace(13)* addrspace(11)* %arrayptr_ptr23.phi.trans.insert, align 16, !dbg !1377, !tbaa !172, !alias.scope !1349, !noalias !167
  %arrayptr2659.pre64 = load double addrspace(13)*, double addrspace(13)* addrspace(11)* addrspacecast (double addrspace(13)** inttoptr (i64 140255166057472 to double addrspace(13)**) to double addrspace(13)* addrspace(11)*), align 1024, !dbg !1380, !tbaa !172, !alias.scope !1349, !noalias !167
  %arrayptr2860.pre67 = load i64 addrspace(13)*, i64 addrspace(13)* addrspace(11)* addrspacecast (i64 addrspace(13)** inttoptr (i64 140255166057344 to i64 addrspace(13)**) to i64 addrspace(13)* addrspace(11)*), align 128, !dbg !1383, !tbaa !172, !alias.scope !1349, !noalias !167
  br label %L51, !dbg !1372

L51:                                              ; preds = %L95, %L32.L51_crit_edge
  %nodecayed.arrayptr2860 = phi {} addrspace(10)* , !dbg !1383
  %nodecayedoff.arrayptr2860 = phi i64 , !dbg !1383
  %arrayptr2860 = phi i64 addrspace(13)* [ %arrayptr2860.pre67, %L32.L51_crit_edge ], [ %arrayptr286068, %L95 ], !dbg !1383
  %nodecayed.arrayptr2659 = phi {} addrspace(10)* , !dbg !1380
  %nodecayedoff.arrayptr2659 = phi i64 , !dbg !1380
  %arrayptr2659 = phi double addrspace(13)* [ %arrayptr2659.pre64, %L32.L51_crit_edge ], [ %arrayptr265965, %L95 ], !dbg !1380
  %nodecayed.arrayptr3249 = phi {} addrspace(10)* 
  %nodecayedoff.arrayptr3249 = phi i64 
  %arrayptr3249 = phi i8 addrspace(13)* [ %arrayptr24.pre, %L32.L51_crit_edge ], [ %arrayptr32, %L95 ]
  %value_phi21 = phi i64 [ 1, %L32.L51_crit_edge ], [ %39, %L95 ]
  %23 = add nsw i64 %value_phi21, -1, !dbg !1377
  %24 = bitcast i8 addrspace(13)* %arrayptr3249 to double addrspace(13)*, !dbg !1377
  %25 = getelementptr inbounds double, double addrspace(13)* %24, i64 %23, !dbg !1377
  %26 = bitcast double addrspace(13)* %25 to i64 addrspace(13)*, !dbg !1377
  %arrayref58 = load i64, i64 addrspace(13)* %26, align 8, !dbg !1377, !tbaa !175, !alias.scope !178, !noalias !179
  %27 = lshr i64 %arrayref58, 13, !dbg !1385
  %28 = and i64 %27, 255, !dbg !1389
  %29 = and i64 %arrayref58, 4096, !dbg !1393
  %30 = icmp eq i64 %29, 0, !dbg !1393
  %31 = sub nsw i64 0, %27, !dbg !1400
  %32 = select i1 %30, i64 %27, i64 %31, !dbg !1402
  %33 = getelementptr inbounds double, double addrspace(13)* %arrayptr2659, i64 %28, !dbg !1380
  %arrayref27 = load double, double addrspace(13)* %33, align 8, !dbg !1380, !tbaa !175, !alias.scope !178, !noalias !179
  %34 = sitofp i64 %32 to double, !dbg !1404
  %35 = fmul double %arrayref27, %34, !dbg !1414
  %36 = getelementptr inbounds i64, i64 addrspace(13)* %arrayptr2860, i64 %28, !dbg !1383
  %arrayref29 = load i64, i64 addrspace(13)* %36, align 8, !dbg !1383, !tbaa !175, !alias.scope !178, !noalias !179
  %.not61 = icmp ult i64 %27, %arrayref29, !dbg !1416
  br i1 %.not61, label %L95, label %L93, !dbg !1384

L93:                                              ; preds = %L51
  %37 = call fastcc double @julia_randn_unlikely_3278(i64 noundef signext %28, i64 signext %27, double %35), !dbg !1418
  %arrayptr32.pre = load i8 addrspace(13)*, i8 addrspace(13)* addrspace(11)* %arrayptr_ptr23.phi.trans.insert, align 16, !dbg !1419, !tbaa !172, !alias.scope !1349, !noalias !167
  %.pre = bitcast i8 addrspace(13)* %arrayptr32.pre to double addrspace(13)*, !dbg !1419
  %arrayptr2659.pre = load double addrspace(13)*, double addrspace(13)* addrspace(11)* addrspacecast (double addrspace(13)** inttoptr (i64 140255166057472 to double addrspace(13)**) to double addrspace(13)* addrspace(11)*), align 1024, !dbg !1380, !tbaa !172, !alias.scope !1349, !noalias !167
  %arrayptr2860.pre = load i64 addrspace(13)*, i64 addrspace(13)* addrspace(11)* addrspacecast (i64 addrspace(13)** inttoptr (i64 140255166057344 to i64 addrspace(13)**) to i64 addrspace(13)* addrspace(11)*), align 128, !dbg !1383, !tbaa !172, !alias.scope !1349, !noalias !167
  br label %L95, !dbg !1355

L95:                                              ; preds = %L93, %L51
  %nodecayed.arrayptr286068 = phi {} addrspace(10)* 
  %nodecayedoff.arrayptr286068 = phi i64 
  %arrayptr286068 = phi i64 addrspace(13)* [ %arrayptr2860, %L51 ], [ %arrayptr2860.pre, %L93 ]
  %nodecayed.arrayptr265965 = phi {} addrspace(10)* 
  %nodecayedoff.arrayptr265965 = phi i64 
  %arrayptr265965 = phi double addrspace(13)* [ %arrayptr2659, %L51 ], [ %arrayptr2659.pre, %L93 ]
  %nodecayed..pre-phi = phi {} addrspace(10)* , !dbg !1419
  %nodecayedoff..pre-phi = phi i64 , !dbg !1419
  %.pre-phi = phi double addrspace(13)* [ %24, %L51 ], [ %.pre, %L93 ], !dbg !1419
  %nodecayed.arrayptr32 = phi {} addrspace(10)* , !dbg !1419
  %nodecayedoff.arrayptr32 = phi i64 , !dbg !1419
  %arrayptr32 = phi i8 addrspace(13)* [ %arrayptr3249, %L51 ], [ %arrayptr32.pre, %L93 ], !dbg !1419
  %value_phi30 = phi double [ %35, %L51 ], [ %37, %L93 ]
  %38 = getelementptr inbounds double, double addrspace(13)* %.pre-phi, i64 %23, !dbg !1419
  store double %value_phi30, double addrspace(13)* %38, align 8, !dbg !1419, !tbaa !175, !alias.scope !178, !noalias !1352
  %.not62 = icmp eq i64 %value_phi21, %arraylen16, !dbg !1420
  %39 = add nuw nsw i64 %value_phi21, 1, !dbg !1421
  br i1 %.not62, label %L108, label %L51, !dbg !1422

L108:                                             ; preds = %L95, %L32, %L16, %L4
  ret void, !dbg !1423
}

Could not analyze garbage collection behavior of
 v0:   %arrayptr2860.pre67 = load i64 addrspace(13)*, i64 addrspace(13)* addrspace(11)* addrspacecast (i64 addrspace(13)** inttoptr (i64 140255166057344 to i64 addrspace(13)**) to i64 addrspace(13)* addrspace(11)*), align 128, !dbg !126, !tbaa !79, !alias.scope !81, !noalias !56
 v: i64 addrspace(13)* addrspace(11)* addrspacecast (i64 addrspace(13)** inttoptr (i64 140255166057344 to i64 addrspace(13)**) to i64 addrspace(13)* addrspace(11)*)
 offset: i64 0
 hasload: true

Stacktrace:
 [1] getindex
   @ ./essentials.jl:13
 [2] _randn
   @ ~/.julia/juliaup/julia-1.10.0-rc1+0.x64.linux.gnu/share/julia/stdlib/v1.10/Random/src/normal.jl:66
 [3] randn!
   @ ~/.julia/juliaup/julia-1.10.0-rc1+0.x64.linux.gnu/share/julia/stdlib/v1.10/Random/src/normal.jl:240
 [4] randn
   @ ~/.julia/juliaup/julia-1.10.0-rc1+0.x64.linux.gnu/share/julia/stdlib/v1.10/Random/src/normal.jl:252
 [5] randn
   @ ~/.julia/juliaup/julia-1.10.0-rc1+0.x64.linux.gnu/share/julia/stdlib/v1.10/Random/src/normal.jl:258
 [6] multiple call sites
   @ unknown:0

Stacktrace:
  [1] (::Enzyme.Compiler.var"#getparent#350"{…})(v::LLVM.ConstantExpr, offset::LLVM.ConstantInt, hasload::Bool)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/6SuJO/src/compiler/optimize.jl:292
  [2] (::Enzyme.Compiler.var"#getparent#350"{…})(v::LLVM.LoadInst, offset::LLVM.ConstantInt, hasload::Bool)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/6SuJO/src/compiler/optimize.jl:239
  [3] nodecayed_phis!(mod::LLVM.Module)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/6SuJO/src/compiler/optimize.jl:295
  [4] optimize!
    @ ~/.julia/packages/Enzyme/6SuJO/src/compiler/optimize.jl:1237 [inlined]
  [5] codegen(output::Symbol, job::GPUCompiler.CompilerJob{…}; libraries::Bool, deferred_codegen::Bool, optimize::Bool, toplevel::Bool, strip::Bool, validate::Bool, only_entry::Bool, parent_job::Nothing)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/6SuJO/src/compiler.jl:4656
  [6] codegen
    @ ~/.julia/packages/Enzyme/6SuJO/src/compiler.jl:4281 [inlined]
  [7] _thunk(job::GPUCompiler.CompilerJob{Enzyme.Compiler.EnzymeTarget, Enzyme.Compiler.EnzymeCompilerParams}, postopt::Bool) (repeats 2 times)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/6SuJO/src/compiler.jl:5272
  [8] cached_compilation
    @ ~/.julia/packages/Enzyme/6SuJO/src/compiler.jl:5306 [inlined]
  [9] (::Enzyme.Compiler.var"#485#486"{DataType, UnionAll, DataType, Enzyme.API.CDerivativeMode, Tuple{Bool, Bool}, Int64, Bool, Bool, UInt64, DataType})(ctx::LLVM.Context)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/6SuJO/src/compiler.jl:5372
 [10] JuliaContext(f::Enzyme.Compiler.var"#485#486"{DataType, UnionAll, DataType, Enzyme.API.CDerivativeMode, Tuple{Bool, Bool}, Int64, Bool, Bool, UInt64, DataType})
    @ GPUCompiler ~/.julia/packages/GPUCompiler/U36Ed/src/driver.jl:47
 [11] #s1038#484
    @ ~/.julia/packages/Enzyme/6SuJO/src/compiler.jl:5324 [inlined]
 [12] 
    @ Enzyme.Compiler ./none:0
 [13] (::Core.GeneratedFunctionStub)(::UInt64, ::LineNumberNode, ::Any, ::Vararg{Any})
    @ Core ./boot.jl:600
 [14] autodiff(::ReverseMode{false, FFIABI}, f::Const{typeof(bar)}, ::Type{Active}, args::Duplicated{Vector{Matrix{Float64}}})
    @ Enzyme ~/.julia/packages/Enzyme/6SuJO/src/Enzyme.jl:209
 [15] autodiff(::ReverseMode{false, FFIABI}, ::typeof(bar), ::Type, ::Duplicated{Vector{Matrix{Float64}}})
    @ Enzyme ~/.julia/packages/Enzyme/6SuJO/src/Enzyme.jl:224
 [16] top-level scope
    @ ~/worktree/BugReports/EnzymeTestUtils.jl-return-type-dispath/main.jl:35

</details>

**Comment by wsmoses** [comment]
The error here is not that the rule isn't selected, but that Enzyme did not understand some code generated by the julia compiler, so it errored out during the compilation phase.

Regardless, fixed in https://github.com/EnzymeAD/Enzyme.jl/pull/1179
