### ISSUE TITLE
How to build documentation locally?

### ISSUE THREAD

**Issue by gdalle** [EnzymeAD/Enzyme.jl#1189]
While writing #1187 I tried to build the docs locally by following this process (from the `CI.yml` file):

```julia
pkg> dev ./lib/EnzymeCore
pkg> dev ./lib/EnzymeTestUtils
pkg> dev .
pkg> instantiate
julia> include("docs/make.jl")
```

but Julia still complained about missing dependencies and asked me to instantiate. What am I missing?

**Comment by lassepe** [comment]
Did you run the commands above in a REPL that has the docs env activated (i.e., `julia --project=docs/`)? If so, that's exactly what I do offline and it works well.
