### ISSUE TITLE
Error with Flux GRU layer

### ISSUE THREAD

**Issue by jgreener64** [EnzymeAD/Enzyme.jl#1261]
I am on Julia 1.10.0, Enzyme main (ba58bcb) and Flux 0.14.10.
```julia
using Enzyme, Flux
loss(model, x) = sum(model(x))
model = GRU(3 => 5)
x = randn(Float32, 3, 10)
d_model = Flux.fmap(model) do x
    x isa Array ? zero(x) : x
end
Enzyme.autodiff(Reverse, loss, Active, Duplicated(model, d_model), Const(x))
```
See the [error.txt](https://github.com/EnzymeAD/Enzyme.jl/files/14091089/error.txt) and the [printall_error.txt](https://github.com/EnzymeAD/Enzyme.jl/files/14091080/printall_error.txt).

**Comment by wsmoses** [comment]
Are you able to minimize this by chance (and potentially open issues for the other problems you found)?

**Comment by jgreener64** [comment]
I think this is the minimal error. On Enzyme main (5e4e2ef) and Julia 1.10.2:
```julia
using Enzyme

loss(gxs, ghs) = sum(gxs .+ ghs)

gxs = rand(5, 10)
ghs = rand(5)

gxs = view(gxs, 1:5, 1:10)
ghs = view(ghs, 1:5)

loss(gxs, ghs)

autodiff(
    Reverse,
    loss,
    Active,
    Duplicated(gxs, gxs),
    Duplicated(ghs, ghs),
)
```
The [error.txt](https://github.com/EnzymeAD/Enzyme.jl/files/14548281/error.txt) and [printall_error.txt](https://github.com/EnzymeAD/Enzyme.jl/files/14548283/printall_error.txt) are attached.

**Comment by wsmoses** [comment]
@jgreener64 @CarloLucibello the last example now works on main, going to close this. Please reopen if it persists.
