### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by swilliamson7** [EnzymeAD/Enzyme.jl#1284]
Unknown if this is Enzyme or Checkpointing (I have told Michel about it too). Just run this script from inside the folder `my_scripts` to cause it to happen: https://github.com/swilliamson7/ShallowWaters.jl/blob/zannabolton/my_scripts/run_checkpointing.jl

**Comment by vchuravy** [comment]
On my local system 128GB + 64GB swap the Julia process spikes to 80GB and then the OOM reaper comes in

```
[84116.519284] Out of memory: Killed process 195644 (julia) total-vm:145918300kB, anon-rss:87846568kB, file-rss:440kB, shmem-rss:0kB, UID:1000 pgtables:283476kB oom_score_adj:200
[84138.036878] oom_reaper: reaped process 195644 (julia), now anon-rss:648kB, file-rss:440kB, shmem-rss:0kB
```

**Comment by vchuravy** [comment]
These seems also great as a performance stress test for type tree.

![image](https://github.com/EnzymeAD/Enzyme.jl/assets/145258/f7effd1c-a055-4d65-b93a-37e85f7351e6)

**Comment by vchuravy** [comment]
Also these allocation seem to not be Julia allocations:
For Ndays=60
```
[ Info: Revolve: Number of checkpoints: 116
[ Info: Revolve: Number of steps: 13465
[ Info: Prediction:
[ Info: Forward steps   : 33374
[ Info: Overhead factor : 2.4783900193078865
warning: didn't implement memmove, using memcpy as fallback which can result in errors
504.732108 seconds (49.93 M allocations: 3.709 GiB, 0.23% gc time, 68.33% compilation time)
```

**Comment by swilliamson7** [comment]
What would be allocating memory here if not Julia? Or do you just mean that they seem to be caused by a package?

**Comment by vchuravy** [comment]
> What would be allocating memory here if not Julia? 

Enzyme for it's internal caches.

**Comment by swilliamson7** [comment]
@michel2323 Here's a minor thread of stuff Valentin noticed!

**Comment by vchuravy** [comment]
The profiler is sadly not handling the flame graphs well.

**Comment by michel2323** [comment]
As a sidenote, since updating to the latest `Enzyme#main` with `Enymze_jll@0.0.100+0` I get this:
```
[ Info: Revolve: Number of checkpoints: 116
[ Info: Revolve: Number of steps: 13465
[ Info: Prediction:
[ Info: Forward steps   : 33374
[ Info: Overhead factor : 2.4783900193078865
ERROR: LoadError: InexactError: check_top_bit(UInt32, -1)
Stacktrace:
  [1] throw_inexacterror(f::Symbol, ::Type{UInt32}, val::Int32)
    @ Core ./boot.jl:634
  [2] check_top_bit
    @ Core ./boot.jl:648 [inlined]
  [3] toUInt32
    @ Core ./boot.jl:747 [inlined]
  [4] UInt32
    @ Core ./boot.jl:788 [inlined]
  [5] Integer
    @ CEnum /disk/mschanen/julia_depot/packages/CEnum/B6ahP/src/CEnum.jl:19 [inlined]
  [6] cconvert
    @ CEnum /disk/mschanen/julia_depot/packages/CEnum/B6ahP/src/CEnum.jl:20 [inlined]
  [7] LLVMAddCallSiteAttribute(C::LLVM.CallInst, Idx::LLVM.API.__JL_Ctag_85, A::LLVM.StringAttribute)
```
More in the attached log.
[out.log](https://github.com/EnzymeAD/Enzyme.jl/files/14249333/out.log)

**Comment by michel2323** [comment]
@vchuravy The above error is due to updating `LLVM@v6.4.2` as defined in the Manifest.toml to `LLVM@6.5.0`. So this might be something unrelated.

**Comment by wsmoses** [comment]
@michel2323 I just pushed a fix for that to main.

**Comment by michel2323** [comment]
This is me. The augmented forward call is not picked up. The tests in Checkpointing.jl happily report success. I found the issue. I commented out a line that I shouldn't have. I go in my corner now and push a fix once I'm 100% sure it works.
