### ISSUE TITLE
IOError creating a development build

### ISSUE THREAD

**Issue by maxaehle** [EnzymeAD/Enzyme.jl#1291]
I'm trying to follow the instructions in [dev_docs.md](https://github.com/EnzymeAD/Enzyme.jl/blob/0ea561f9ce655861619b7f3472af3409611dd73d/docs/src/dev_docs.md) to create a development build of Enzyme.jl, but they do not work on my system (Ubuntu 22.04, julia 1.10.0 with LLVM 15.0.7jl). I have not worked a lot with Julia yet and would be happy about some hints what I could be doing wrong. 

I started with
```bash
git clone https://github.com/EnzymeAD/Enzyme.jl
cd Enzyme.jl
julia --project=.
```
The documentation is a bit ambiguous about whether Enzyme or Enzyme.jl should be cloned, but this is how I understand it. Now Julia opens. When I say
```julia
using Enzyme_jll
```
as suggested by the documentation, this gives an error:
```
ERROR: ArgumentError: Package Enzyme_jll [7cc45869-7501-5eee-bdea-0790c847d4ef] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.

Stacktrace:
  [1] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:1920
...
 [11] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1740
```
I then  said `] instantiate`, and after that `using Enzyme_jll` worked. Next, `Enzyme_jll.dev_jll()`  gives the following error message:
```
   Resolving package versions...
    Updating `/tmp/jl_l7byio/Project.toml`
  [7cc45869] + Enzyme_jll v0.0.101+0 `~/.julia/dev/Enzyme_jll`
    Updating `/tmp/jl_l7byio/Manifest.toml`
  [692b3bcd] + JLLWrappers v1.5.0
  [21216c6a] + Preferences v1.4.1
  [7cc45869] + Enzyme_jll v0.0.101+0 `~/.julia/dev/Enzyme_jll`
  [0dad84c5] + ArgTools v1.1.1
...
  [3f19e933] + p7zip_jll v17.4.0+2
ERROR: IOError: open("/home/aehle/.julia/artifacts/0d852fd29f0de6a6ab5c6441bef3d60cead9ab76", 0, 0): no such file or directory (ENOENT)
Stacktrace:
  [1] uv_error
    @ Base ./libuv.jl:100 [inlined]
  [2] open(path::String, flags::UInt8, mode::Int64)
    @ Base.Filesystem ./filesystem.jl:121
...
 [10] dev_jll()
    @ Enzyme_jll ~/.julia/packages/JLLWrappers/pG9bm/src/toplevel_generators.jl:93
 [11] top-level scope
    @ REPL[5]:1
```

Any idea what I'm doing wrong?

**Comment by wsmoses** [comment]
Please see the new recommended way for creating a development build here: https://github.com/EnzymeAD/Enzyme.jl/pull/1436

If that doesn't resolve your issue, please reopen.
