### ISSUE TITLE
Long Enzyme compile times

### ISSUE THREAD

**Issue by swilliamson7** [EnzymeAD/Enzyme.jl#1296]
Just opening an issue about the compile time stuff, I think Michel has already filled you guys in a little. Basically we're facing really long initial compile times with Enzyme with [this script](https://github.com/swilliamson7/ShallowWaters.jl/blob/zannabolton/my_scripts/run_checkpointing.jl). Michel and I aren't sure why this is happening. I did need to add this line `Enzyme.API.maxtypeoffset!(3500)` to make the code differentiable, which I think Billy might have warned me increases the compile time? In any case, figured having a formal issue about this could be nice!

**Comment by wsmoses** [comment]
So from my understandinf of the profile of the code earlier, this should now be resolved. If any other code you have (or the same one) exhibits bad compile times please open an issue
