### ISSUE TITLE
Unexpected zero derivative

### ISSUE THREAD

**Issue by swilliamson7** [EnzymeAD/Enzyme.jl#1304]
Not sure if this is an Enzyme issue or a my code issue, but Enzyme is returning a zero where I would expect a non-zero value. I'm using Checkpointing + Enzyme to try and compute a derivative of a cost function w.r.t. a specific parameter, and running [this script](https://github.com/swilliamson7/ShallowWaters.jl/blob/zannabolton/my_scripts/checkpointing_debugging.jl) will attempt to do it. It successfully runs, the relevant variables in the output structures `S` and `dS` are `S.parameters.J` (this is the total value of the cost function), and `dS.parameters.\gamma\_0` (this is the derivative I want). I did a finite difference calculation to find the derivative and I really think it shouldn't be zero, so I'm not quite sure what's happening. 

Happy to provide more info if needed!

**Comment by swilliamson7** [comment]
An update to this, I think the zero is happening because the initial derivative is being chosen incorrectly/something is happening with the initial derivative. This could fall under either Enzyme or Checkpointing, I'm not sure which is causing it, but I get a correct non-zero value if I modify my code slightly so it's not quite a full issue

**Comment by wsmoses** [comment]
@swilliamson7 I assume this is resolved by our debug session earlier? Please reopen if not
