### ISSUE TITLE
Multiple issues when using a global variable

### ISSUE THREAD

**Issue by ArnoStrouwen** [EnzymeAD/Enzyme.jl#1313]
I couldn't find much info on how Enzyme deals with global variables in the documentation, and am running into various issues in SciML usecases:
```julia
using OrdinaryDiffEq, SciMLSensitivity, Enzyme
Enzyme.API.typeWarning!(false)
prob2 = ODEProblem((du, u, p, t) -> du .= u .* p, [2.0], (0.0, 1.0), [3.0])
function loss(p)
    sum(solve(prob2, Tsit5(), p = p, saveat = 0.1))
end
p = [3.0]
Enzyme.gradient(Reverse, loss, p)
```
```
ERROR: AssertionError: @NamedTuple{p::Vector{Float64}, saveat::Float64} has mixed internal activity types`
```
marking the prob as `const` works:
```jl
using OrdinaryDiffEq, SciMLSensitivity, Enzyme
Enzyme.API.typeWarning!(false)
const prob = ODEProblem((du, u, p, t) -> du .= u .* p, [2.0], (0.0, 1.0), [3.0])
function loss(p)
    sum(solve(prob, Tsit5(), p = p, saveat = 0.1))
end
p = [3.0]
Enzyme.gradient(Reverse, loss, p)
```
Then there are other errors still when making the prob local:
```jl
using OrdinaryDiffEq, SciMLSensitivity, Enzyme
Enzyme.API.typeWarning!(false)
function loss(p)
    prob2 = ODEProblem((du, u, p, t) -> du .= u .* p, [2.0], (0.0, 1.0), [3.0])
    sum(solve(prob2, Tsit5(), p = p, saveat = 0.1))
end
p = [3.0]
Enzyme.gradient(Reverse, loss, p)
```
```
ERROR: Enzyme execution failed.
Enzyme: Not yet implemented augmented forward for jl_f__apply_iterate (true, true, iterate, Core.apply_type, 7, 6)
```
Removing the `saveat` keyword gives another large error:
```jl
using OrdinaryDiffEq, SciMLSensitivity, Enzyme
Enzyme.API.typeWarning!(false)
prob2 = ODEProblem((du, u, p, t) -> du .= u .* p, [2.0], (0.0, 1.0), [3.0])
function loss(p)
    sum(solve(prob2, Tsit5(), p = p))
end
p = [3.0]
Enzyme.gradient(Reverse, loss, p)
```
<details>
  <summary>Click me</summary>
ERROR: Enzyme execution failed.
Enzyme cannot deduce type
Current scope:
; Function Attrs: mustprogress willreturn
define double @preprocess_julia_sum_8560_inner.1({ {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, { { [1 x [4 x {} addrspace(10)*]], [1 x i8] }, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, i8, { {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)* }, i8 }, i8, i64, {} addrspace(10)*, i32 } %0) local_unnamed_addr #6 !dbg !42 {
entry:
  %.fca.0.extract = extractvalue { {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, { { [1 x [4 x {} addrspace(10)*]], [1 x i8] }, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, i8, { {} addrspace(10)*, {} addrspace(10)*, 
  ...
  ...
  ...
  %.sroa.29.0..sroa_idx = getelementptr inbounds i8, i8 addrspace(10)* %4, i64 224, !dbg !46
  %.sroa.29.0..sroa_cast = bitcast i8 addrspace(10)* %.sroa.29.0..sroa_idx to {} addrspace(10)* addrspace(10)*, !dbg !46
  store {} addrspace(10)* %.fca.7.extract, {} addrspace(10)* addrspace(10)* %.sroa.29.0..sroa_cast, align 8, !dbg !46, !alias.scope !26, !noalias !51
  %.sroa.30.0..sroa_idx = getelementptr inbounds i8, i8 addrspace(10)* %4, i64 232, !dbg !46
  %.sroa.30.0..sroa_cast = bitcast i8 addrspace(10)* %.sroa.30.0..sroa_idx to i32 addrspace(10)*, !dbg !46
  store i32 %.fca.8.extract, i32 addrspace(10)* %.sroa.30.0..sroa_cast, align 8, !dbg !46, !alias.scope !26, !noalias !51
  %5 = call nonnull {} addrspace(10)* ({} addrspace(10)* ({} addrspace(10)*, {} addrspace(10)**, i32, {} addrspace(10)*)*, {} addrspace(10)*, {} addrspace(10)*, ...) @julia.call2({} addrspace(10)* ({} addrspace(10)*, {} addrspace(10)**, i32, {} addrspace(10)*)* noundef nonnull @ijl_invoke, {} addrspace(10)* noundef addrspacecast ({}* inttoptr (i64 140383588961904 to {}*) to {} addrspace(10)*), {} addrspace(10)* noundef addrspacecast ({}* inttoptr (i64 140384874421440 to {}*) to {} addrspace(10)*), {} addrspace(10)* addrspacecast ({}* inttoptr (i64 140386583753760 to {}*) to {} addrspace(10)*), {} addrspace(10)* addrspacecast ({}* inttoptr (i64 140386562298080 to {}*) to {} addrspace(10)*), {} addrspace(10)* addrspacecast ({}* inttoptr (i64 140386556991360 to {}*) to {} addrspace(10)*), {} addrspace(10)* addrspacecast ({}* inttoptr (i64 140386602006816 to {}*) to {} addrspace(10)*), {} addrspace(10)* nonnull %box.i) #11, !dbg !46
  %6 = bitcast {} addrspace(10)* %5 to double addrspace(10)*, !dbg !44
  %unbox.i = load double, double addrspace(10)* %6, align 8, !dbg !44, !tbaa !36, !alias.scope !40, !noalias !41
  ret double %unbox.i, !dbg !43
}

Cannot deduce adding type of: { {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, { { [1 x [4 x {} addrspace(10)*]], [1 x i8] }, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, i8, { {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)*, {} addrspace(10)* }, i8 }, i8, i64, {} addrspace(10)*, i32 } %0
 + idxs {i32 8,}

Stacktrace:
  [1] throwerr(cstr::Cstring)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/qRjan/src/compiler.jl:1288
  [2] sum
    @ ~/.julia/packages/RecursiveArrayTools/dzBRE/src/vector_of_array.jl:0 [inlined]
  [3] diffejulia_sum_8560_inner_1wrap
    @ ~/.julia/packages/RecursiveArrayTools/dzBRE/src/vector_of_array.jl:0
  [4] macro expansion
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/qRjan/src/compiler.jl:5377 [inlined]
  [5] enzyme_call(::Val{…}, ::Ptr{…}, ::Type{…}, ::Type{…}, ::Val{…}, ::Type{…}, ::Type{…}, ::Const{…}, ::Type{…}, ::Duplicated{…}, ::Float64, ::@NamedTuple{…})
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/qRjan/src/compiler.jl:5055
  [6] (::Enzyme.Compiler.AdjointThunk{Ptr{…}, Const{…}, Active{…}, Tuple{…}, Val{…}, @NamedTuple{…}})(::Const{typeof(sum)}, ::Duplicated{ODESolution{…}}, ::Vararg{Any})
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/qRjan/src/compiler.jl:5003
  [7] runtime_generic_rev(activity::Type{…}, width::Val{…}, ModifiedBetween::Val{…}, tape::Enzyme.Compiler.Tape{…}, f::typeof(sum), df::Nothing, primal_1::ODESolution{…}, shadow_1_1::ODESolution{…})
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/qRjan/src/rules/jitrules.jl:285
  [8] loss
    @ ./REPL[5]:2 [inlined]
  [9] diffejulia_loss_2327wrap
    @ ./REPL[5]:0
 [10] macro expansion
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/qRjan/src/compiler.jl:5377 [inlined]
 [11] enzyme_call
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/qRjan/src/compiler.jl:5055 [inlined]
 [12] AdjointThunk
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/qRjan/src/compiler.jl:5003 [inlined]
 [13] autodiff(::ReverseMode{false, FFIABI}, f::Const{typeof(loss)}, ::Type{Active}, args::Duplicated{Vector{Float64}})
    @ Enzyme ~/.julia/packages/Enzyme/qRjan/src/Enzyme.jl:203
 [14] autodiff
    @ ~/.julia/packages/Enzyme/qRjan/src/Enzyme.jl:224 [inlined]
 [15] gradient(::ReverseMode{false, FFIABI}, f::Function, x::Vector{Float64})
    @ Enzyme ~/.julia/packages/Enzyme/qRjan/src/Enzyme.jl:805
 [16] top-level scope
    @ REPL[7]:1
</details>
Defining the problem in a slightly different way:

```jl
using OrdinaryDiffEq, SciMLSensitivity, Enzyme
Enzyme.API.typeWarning!(false)
prob2 = ODEProblem((du, u, p, t) -> du .= u .* p, [2.0], (0.0, 1.0), [3.0])
function loss(p)
    prob3 = remake(prob2, p = p)
    sum(solve(prob3, Tsit5(), saveat = 0.1))
end
p = [3.0]
Enzyme.gradient(Reverse, loss, p)
```
<details>
  <summary>Click me</summary>
ERROR: Enzyme execution failed.
Mismatched activity for:   store atomic {} addrspace(10)* %getfield3.i, {} addrspace(10)* addrspace(11)* %15 release, align 8, !dbg !46, !tbaa !36, !alias.scope !40, !noalias !52 const val:   %getfield3.i = load atomic {} addrspace(10)*, {} addrspace(10)* addrspace(11)* %7 unordered, align 8, !dbg !34, !tbaa !36, !alias.scope !40, !noalias !41, !nonnull !7, !dereferenceable !42, !align !43
Type tree: {[-1]:Pointer, [-1,0]:Pointer, [-1,0,-1]:Float@double, [-1,8]:Integer, [-1,9]:Integer, [-1,10]:Integer, [-1,11]:Integer, [-1,12]:Integer, [-1,13]:Integer, [-1,14]:Integer, [-1,15]:Integer, [-1,16]:Integer, [-1,17]:Integer, [-1,18]:Integer, [-1,19]:Integer, [-1,20]:Integer, [-1,21]:Integer, [-1,22]:Integer, [-1,23]:Integer, [-1,24]:Integer, [-1,25]:Integer, [-1,26]:Integer, [-1,27]:Integer, [-1,28]:Integer, [-1,29]:Integer, [-1,30]:Integer, [-1,31]:Integer, [-1,32]:Integer, [-1,33]:Integer, [-1,34]:Integer, [-1,35]:Integer, [-1,36]:Integer, [-1,37]:Integer, [-1,38]:Integer, [-1,39]:Integer}
You may be using a constant variable as temporary storage for active memory (https://enzyme.mit.edu/julia/stable/#Activity-of-temporary-storage). If not, please open an issue, and either rewrite this variable to not be conditionally active or use Enzyme.API.runtimeActivity!(true) as a workaround for now

Stacktrace:
 [1] _
   @ ~/.julia/packages/SciMLBase/Dwomw/src/problems/ode_problems.jl:118
 [2] ODEProblem
   @ ~/.julia/packages/SciMLBase/Dwomw/src/problems/ode_problems.jl:111
 [3] #remake#620
   @ ~/.julia/packages/SciMLBase/Dwomw/src/remake.jl:130
 [4] remake
   @ ~/.julia/packages/SciMLBase/Dwomw/src/remake.jl:51
 [5] remake
   @ ~/.julia/packages/SciMLBase/Dwomw/src/remake.jl:0

Stacktrace:
  [1] throwerr(cstr::Cstring)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/qRjan/src/compiler.jl:1288
  [2] _
    @ ~/.julia/packages/SciMLBase/Dwomw/src/problems/ode_problems.jl:118 [inlined]
  [3] ODEProblem
    @ ~/.julia/packages/SciMLBase/Dwomw/src/problems/ode_problems.jl:111 [inlined]
  [4] #remake#620
    @ ~/.julia/packages/SciMLBase/Dwomw/src/remake.jl:130 [inlined]
  [5] remake
    @ ~/.julia/packages/SciMLBase/Dwomw/src/remake.jl:51 [inlined]
  [6] remake
    @ ~/.julia/packages/SciMLBase/Dwomw/src/remake.jl:0 [inlined]
  [7] augmented_julia_remake_3982_inner_1wrap
    @ ~/.julia/packages/SciMLBase/Dwomw/src/remake.jl:0
  [8] macro expansion
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/qRjan/src/compiler.jl:5377 [inlined]
  [9] enzyme_call(::Val{…}, ::Ptr{…}, ::Type{…}, ::Type{…}, ::Val{…}, ::Type{…}, ::Type{…}, ::Const{…}, ::Type{…}, ::Duplicated{…}, ::Const{…}, ::Const{…})
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/qRjan/src/compiler.jl:5055
 [10] (::Enzyme.Compiler.AugmentedForwardThunk{Ptr{…}, Const{…}, Duplicated{…}, Tuple{…}, Val{…}, Val{…}(), @NamedTuple{…}})(::Const{typeof(Core.kwcall)}, ::Duplicated{@NamedTuple{…}}, ::Vararg{Any})
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/qRjan/src/compiler.jl:5008
 [11] runtime_generic_augfwd(activity::Type{…}, width::Val{…}, ModifiedBetween::Val{…}, RT::Val{…}, f::typeof(Core.kwcall), df::Nothing, primal_1::@NamedTuple{…}, shadow_1_1::@NamedTuple{…}, primal_2::typeof(remake), shadow_2_1::Nothing, primal_3::ODEProblem{…}, shadow_3_1::Nothing)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/qRjan/src/rules/jitrules.jl:179
 [12] loss
    @ ./REPL[5]:2 [inlined]
 [13] augmented_julia_loss_2324wrap
    @ ./REPL[5]:0
 [14] macro expansion
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/qRjan/src/compiler.jl:5377 [inlined]
 [15] enzyme_call
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/qRjan/src/compiler.jl:5055 [inlined]
 [16] AugmentedForwardThunk
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/qRjan/src/compiler.jl:5008 [inlined]
 [17] autodiff(::ReverseMode{false, FFIABI}, f::Const{typeof(loss)}, ::Type{Active}, args::Duplicated{Vector{Float64}})
    @ Enzyme ~/.julia/packages/Enzyme/qRjan/src/Enzyme.jl:198
 [18] autodiff
    @ ~/.julia/packages/Enzyme/qRjan/src/Enzyme.jl:224 [inlined]
 [19] gradient(::ReverseMode{false, FFIABI}, f::Function, x::Vector{Float64})
    @ Enzyme ~/.julia/packages/Enzyme/qRjan/src/Enzyme.jl:805
 [20] top-level scope
    @ REPL[7]:1
</details>

However, no mutation as described in: https://enzyme.mit.edu/julia/stable/#Activity-of-temporary-storage seems to be occuring here?

**Comment by wsmoses** [comment]
This is a lot to have in one issue, splitting up any outstanding issues would be helpful.

Your first issue is described in docs here: https://github.com/EnzymeAD/Enzyme.jl/pull/1314/files

The `Enzyme: Not yet implemented augmented forward for jl_f__apply_iterate (true, true, iterate, Core.apply_type, 7, 6)` issue says that your code has a type unstable tuple operator, which we don't currently have derivatives implemented for. I'd recommend looking at the backtrace from where that comes from and type stabilizing it.

Your third issue comes from type analysis being unhappy.

Your fourth issue is likely activity unstable as described in these docs: https://enzymead.github.io/Enzyme.jl/dev/#Caveats-/-Known-issues

**Comment by wsmoses** [comment]
In all of these cases, you probably would be better suited by not using a global variable, but calling autodiff and passing both arguments explicitly to a loss function.

**Comment by ArnoStrouwen** [comment]
> This is a lot to have in one issue, splitting up any outstanding issues would be helpful.

I can make separate issues if you want, for those parts that warrant further investigation, I did not want to spam you.

> your code has a type unstable

The issue with the type unstable iteration can be solved by `ODEProblem{true}` instead of `ODEProblem`. I'm not sure if you meant the rule for unstable iteration has simply not yet been written, or if it is impossible to do so. The average SciML user will often write loss functions which are type unstable.

> In all of these cases, you probably would be better suited by not using a global variable, but calling autodiff and passing both arguments explicitly to a loss function.

While I agree with you and write my own personal projects in this style, the use of global variables is the predominant way that universal differential equation code is written in. We would this be fighting an uphill battle there.

Another question, I understand correctly that activity mismatch is different from mixed activity?

**Comment by ChrisRackauckas** [comment]
> While I agree with you and write my own personal projects in this style, the use of global variables is the predominant way that universal differential equation code is written in. We would this be fighting an uphill battle there.

We should change the tutorial. People always just follow the code I write in the tutorial, so we should lead the proverbial horses to proverbial sparkling mineral water.

**Comment by ArnoStrouwen** [comment]
For the unstable activity of `remake`, I'm not sure what is causing it.
I removed all the branches in:
https://github.com/SciML/SciMLBase.jl/blob/master/src/remake.jl#L51
(which calls:
https://github.com/SciML/SciMLBase.jl/blob/master/src/problems/ode_problems.jl#L97),
hardcoding the correct branch for this specific example, and still got the same error.

**Comment by wsmoses** [comment]
> > This is a lot to have in one issue, splitting up any outstanding issues would be helpful.
> 
> I can make separate issues if you want, for those parts that warrant further investigation, I did not want to spam you.
> 
> > your code has a type unstable
> 
> The issue with the type unstable iteration can be solved by `ODEProblem{true}` instead of `ODEProblem`. I'm not sure if you meant the rule for unstable iteration has simply not yet been written, or if it is impossible to do so. The average SciML user will often write loss functions which are type unstable.

It has been partially written, in other words it has been written for some input types, but not all. PR's welcome (though it's a difficult one and relatively rare which is why it hasn't been prioritized yet). This one can probably be added without much difficulty by modifying here to also permit apply_type in addition to tuple: https://github.com/EnzymeAD/Enzyme.jl/blob/d28f2826b5b91d3248109d28e6399e7dc058f013/src/rules/jitrules.jl#L790 .

> > In all of these cases, you probably would be better suited by not using a global variable, but calling autodiff and passing both arguments explicitly to a loss function.
> 
> While I agree with you and write my own personal projects in this style, the use of global variables is the predominant way that universal differential equation code is written in. We would this be fighting an uphill battle there.
> 
> Another question, I understand correctly that activity mismatch is different from mixed activity?

I'm not sure I understand the question?

**Comment by wsmoses** [comment]
And yes please open individual issues for anything here outstanding, there's too many distinct questions here to determine whether the issue is complete.

**Comment by wsmoses** [comment]
Apply iterate, and mixedduplicated both have been added. If there is anything outstanding, please open an issue.
