### ISSUE TITLE
Why is `autodiff_thunk` useful in forward mode?

### ISSUE THREAD

**Issue by gdalle** [EnzymeAD/Enzyme.jl#1335]
I understand the purpose of [`autodiff_thunk` in reverse mode](https://enzymead.github.io/Enzyme.jl/stable/api/#EnzymeCore.autodiff_thunk-Union{Tuple{RABI},%20Tuple{ModifiedBetweenT},%20Tuple{Width},%20Tuple{ReturnShadow},%20Tuple{ReturnPrimal},%20Tuple{A},%20Tuple{FA},%20Tuple{EnzymeCore.ReverseModeSplit{ReturnPrimal,%20ReturnShadow,%20Width,%20ModifiedBetweenT,%20RABI},%20Type{FA},%20Type{A},%20Vararg{Any}}}%20where%20{FA%3C:Annotation,%20A%3C:Annotation,%20ReturnPrimal,%20ReturnShadow,%20Width,%20ModifiedBetweenT,%20RABI%3C:EnzymeCore.ABI}): it allows the creation of a tape so that subsequent pullbacks are evaluated much faster.

What about [`autodiff_thunk` in forward mode](https://enzymead.github.io/Enzyme.jl/stable/api/#EnzymeCore.autodiff_thunk-Union{Tuple{RABI},%20Tuple{A},%20Tuple{FA},%20Tuple{ForwardMode{RABI},%20Type{FA},%20Type{A},%20Vararg{Any}}}%20where%20{FA%3C:Annotation,%20A%3C:Annotation,%20RABI%3C:EnzymeCore.ABI}) though? Does it speed things up?

**Comment by wsmoses** [comment]
If the original code is non-inferrable it may. It also enforces compilation for the specified types, if they differ from the runtime types of the arguments provided.
