### ISSUE TITLE
Illegal instruction error on reverse mode autodiff

### ISSUE THREAD

**Issue by dominic-chang** [EnzymeAD/Enzyme.jl#1339]
I'm running Enzyme in reverse mode on some code on Julia 1.10.2. This however results in a segmentation fault with the following stack trace:
[out.txt](https://github.com/EnzymeAD/Enzyme.jl/files/14544016/out.txt)

**Comment by wsmoses** [comment]
Can you upload the MWE reproducer ?

**Comment by dchang10** [comment]
Apparently I was taking a derivative at a point where the derivative does not exist, so I think it was a mistake on my end

**Comment by wsmoses** [comment]
We still shouldn't crash like this if you're able to upload a reproducer?

**Comment by dchang10** [comment]
Ok, I'll see if I can figure out a code reduction

**Comment by wsmoses** [comment]
@dominic-chang without a reproducer, I can't fix/check if already fixed, so closing. Please reopen if it persists.
