### ISSUE TITLE
Warning with Flux.Bilinear

### ISSUE THREAD

**Issue by CarloLucibello** [EnzymeAD/Enzyme.jl#1341]
When executing the following code
```julia
using Enzyme, Flux
loss(model, x) = sum(model(x))
model = Flux.Bilinear(2 => 3)
x = randn(Float32, 2, 4)
d_model = Flux.fmap(model) do x
    x isa Array ? zero(x) : x
end
Enzyme.autodiff(Reverse, loss, Active, Duplicated(model, d_model), Const(x))
```
I get the Warning (only showing a tiny part)
```
│ 
│ Stacktrace:
│  [1] getproperty
│    @ ./Base.jl:37
│  [2] _wait2
│    @ ./condition.jl:87
└ @ Enzyme.Compiler ~/.julia/packages/GPUCompiler/U36Ed/src/utils.jl:59
┌ Warning: TypeAnalysisDepthLimit
│ LLVM.StoreInst(store atomic {} addrspace(10)* %getfield14, {} addrspace(10)* addrspace(11)* %18 release, align 8, !dbg !171, !tbaa !142, !alias.scope !146, !noalias !174)
│ {[]:Pointer, [0]:Pointer, [0,0]:Pointer, [0,0,0]:Pointer, [0,0,0,0]:Pointer, [0,0,0,0,0]:Pointer, [0,0,0,8]:Pointer, [0,0,0,8,0]:Pointer, [0,0,0,8,0,0]:Pointer,
...
```
I haven't had time to reduce it yet,  but the culprit could be the `NNlib.batched_mul` operation [here](https://github.com/FluxML/Flux.jl/blob/5f84b68bf2a83fe8d6bb92a6887e4e2ae3a3ac40/src/layers/basic.jl#L445)

**Comment by wsmoses** [comment]
So that trace doesnt actually show the error on the inside. Can you post the full error log?

**Comment by CarloLucibello** [comment]
Here is the full output
[out.txt](https://github.com/EnzymeAD/Enzyme.jl/files/14584331/out.txt)

**Comment by wsmoses** [comment]
I don't see any error messages in your trace either -- just warnings.

You can silcence them with `Enzyme.API.typeWarning!(false)` right after importing Enzyme.

**Comment by CarloLucibello** [comment]
Ok. Should `Enzyme.API.typeWarning!(false)` be the default then?

**Comment by wsmoses** [comment]
Yeah that's something I've been leaning towards recently as we've added more type info regardless.

The point of that warning is to let the user know that we've hit a cut off for how much type information Julia is going to provide, which could lead to Enzyme not being able to differentiate a function at all (or as performantly).
