### ISSUE TITLE
Intimidating docs

### ISSUE THREAD

**Issue by gdalle** [EnzymeAD/Enzyme.jl#1344]
I know that the documentation of Enzyme is a work in progress, but it seems a bit intimidating for newcomers.
Here are some ideas I had:
- https://enzymead.github.io/Enzyme.jl/stable/#Caveats-/-Known-issues does not belong on the home page but on a dedicated "Caveats" page
- https://enzymead.github.io/Enzyme.jl/stable/generated/box/ is too complicated as a first tutorial, the autodiff API should come first
- there are some repetitions between https://enzymead.github.io/Enzyme.jl/stable/generated/autodiff/ and https://enzymead.github.io/Enzyme.jl/stable/#Getting-started
- https://enzymead.github.io/Enzyme.jl/stable/generated/custom_rule/ is for advanced users
- https://enzymead.github.io/Enzyme.jl/dev/api/ should use Documenter v1.3 for folding docstrings

Would a restructuring PR be welcome @wsmoses ?

**Comment by wsmoses** [comment]
go for it!

**Comment by wsmoses** [comment]
It may be useful to bring in julia versions of https://enzyme.mit.edu/getting_started/CallingConvention/ or https://enzyme.mit.edu/getting_started/Examples/

The first is partially described here: https://enzyme.mit.edu/julia/stable/api/#EnzymeCore.autodiff-Union{Tuple{RABI},%20Tuple{ReturnPrimal},%20Tuple{A},%20Tuple{FA},%20Tuple{ReverseMode{ReturnPrimal,%20RABI},%20FA,%20Type{A},%20Vararg{Any}}}%20where%20{FA%3C:Annotation,%20A%3C:Annotation,%20ReturnPrimal,%20RABI%3C:EnzymeCore.ABI}

**Comment by wsmoses** [comment]
Since the FAQ PR landed closing this, feel free to open any other issues/PRs
