### ISSUE TITLE
What is ABI?

### ISSUE THREAD

**Issue by gdalle** [EnzymeAD/Enzyme.jl#1345]
Apparently it plays a part in the mode choice?

https://github.com/EnzymeAD/Enzyme.jl/blob/413b70f0312e993c2ebbb5a15353052e627ec094/lib/EnzymeCore/src/EnzymeCore.jl#L180-L185

**Comment by wsmoses** [comment]
It's somewhat intentionally underdocumented at the moment.

Specifically it is used to specify how Enzyme injects the code it produces into the Julia runtime. 

There's presently only one "officially" supported runtime, the DefaultABI aka FFIABI (in which we inject the code into Julia's JIT after we run our own separate compilation).

There's a second "hidden" ABI, InlineABI, which basically causes Enzyme to emit things as an inline llvmcall. It's mostly used by Enzyme devs for debugging, but may also enable support with precompilation. That said the reason it's hidden is that @vchuravy is skeptical of the integration with other components so we intentionally haven't advertised it.

**Comment by wsmoses** [comment]
If curious for specifics, see below:

```llvm

julia> @code_llvm Enzyme.autodiff(Reverse, sin, Active(3.0))
;  @ /Users/wmoses/git/Enzyme.jl/src/Enzyme.jl:317 within `autodiff`
define [1 x [1 x double]] @julia_autodiff_2864([1 x double]* nocapture noundef nonnull readonly align 8 dereferenceable(8) %0) #0 {
guard_exit5:
  %memcpy_refined_src = getelementptr inbounds [1 x double], [1 x double]* %0, i64 0, i64 0
  %1 = load double, double* %memcpy_refined_src, align 8
;  @ /Users/wmoses/git/Enzyme.jl/src/Enzyme.jl:318 within `autodiff` @ /Users/wmoses/git/Enzyme.jl/src/Enzyme.jl:333 @ /Users/wmoses/git/Enzyme.jl/src/Enzyme.jl:309
; ┌ @ /Users/wmoses/git/Enzyme.jl/src/compiler.jl:6067 within `CombinedAdjointThunk`
; │┌ @ /Users/wmoses/git/Enzyme.jl/src/compiler.jl:6190 within `enzyme_call`
; ││┌ @ /Users/wmoses/git/Enzyme.jl/src/compiler.jl:6589 within `macro expansion`
     %2 = call [1 x [1 x double]] inttoptr (i64 5353095168 to [1 x [1 x double]] (double, double)*)(double %1, double 1.000000e+00)
     ret [1 x [1 x double]] %2
; └└└
}

julia> @code_llvm Enzyme.autodiff(ReverseMode{false, InlineABI, false}(), sin, Active(3.0))
;  @ /Users/wmoses/git/Enzyme.jl/src/Enzyme.jl:317 within `autodiff`
define [1 x [1 x double]] @julia_autodiff_2934([1 x double]* nocapture noundef nonnull readonly align 8 dereferenceable(8) %0) #0 {
guard_exit5:
  %memcpy_refined_src = getelementptr inbounds [1 x double], [1 x double]* %0, i64 0, i64 0
  %1 = load double, double* %memcpy_refined_src, align 8
;  @ /Users/wmoses/git/Enzyme.jl/src/Enzyme.jl:318 within `autodiff` @ /Users/wmoses/git/Enzyme.jl/src/Enzyme.jl:333 @ /Users/wmoses/git/Enzyme.jl/src/Enzyme.jl:309
; ┌ @ /Users/wmoses/git/Enzyme.jl/src/compiler.jl:6067 within `CombinedAdjointThunk`
; │┌ @ /Users/wmoses/git/Enzyme.jl/src/compiler.jl:6190 within `enzyme_call`
; ││┌ @ /Users/wmoses/git/Enzyme.jl/src/compiler.jl:6596 within `macro expansion`
     %2 = call fast double @llvm.cos.f64(double %1)
     %unbox3.fca.0.0.insert = insertvalue [1 x [1 x double]] zeroinitializer, double %2, 0, 0
     ret [1 x [1 x double]] %unbox3.fca.0.0.insert
; └└└
}
```

**Comment by gdalle** [comment]
Thanks for the details!

> It's somewhat intentionally underdocumented at the moment.

For the record, I don't think that should ever be a thing. I understand the lack of time and hands to write docs, but refusing to document something because someone else might use it is different.
It's more of a problem with Julia where "the docs is the API", but one can still put this stuff in the "private / internals" part of the API reference?

**Comment by wsmoses** [comment]
there are some (admittedly breif) docs, closing
