### ISSUE TITLE
EnzymeTestUtils tests failing on main

### ISSUE THREAD

**Issue by sethaxen** [EnzymeAD/Enzyme.jl#1349]
From https://github.com/EnzymeAD/Enzyme.jl/pull/1327#issuecomment-1979737864:
> [e6fa10b](https://github.com/EnzymeAD/Enzyme.jl/pull/1282/commits/e6fa10b62ff0c408e346082dca1b543733fe354c) marked some formerly broken EnzymeTestUtils tests as passing, but they were still failing when that PR was merged.

Now (I believe) the same tests segfault, see e.g. https://github.com/EnzymeAD/Enzyme.jl/actions/runs/8274972327/job/22641185285#step:6:266. I think these are the reverse-mode mutating callable tests: https://github.com/EnzymeAD/Enzyme.jl/blob/2f6d5641fcd40804032386d1339fc6ff5448feb9/lib/EnzymeTestUtils/test/test_reverse.jl#L113-L139

**Comment by vchuravy** [comment]
Is this with a locally built version of Enzyme_jll? Currently the packaged version doesn't work with Enzyme.jl main

@wsmoses I do think we really need something like API versioning to stop having these prolonged cases of CI being broken on the packaged Enzyme_jll

**Comment by wsmoses** [comment]
API didn't change. Just the new complex tests don't pass without the new derivative defined internally

**Comment by wsmoses** [comment]
Thus the old jll is fine for all these tests.

The difference is just that Enzyme enabled fast tablegen on by default now, which changed what tests pass in EnzymeTestUtils.

All that should be required here is changing which tests in EnzymeTestUtils pass/fail to match what CI says. No internal changes required

**Comment by vchuravy** [comment]
>  Just the new complex tests don't pass without the new derivative defined internally


Then the tests should have been guarded by checking the version of Enzyme proper. We can't use `Base.pkgversion(Enzyme_jll)` since the version of the Julia package and the C++ library package don't necessarily align. 

So being able to query the version of Enzyme proper would prevent us from being in the position where for multiple weeks CI us red.

**Comment by wsmoses** [comment]
That's possible to do in Julia?

**Comment by vchuravy** [comment]
> That's possible to do in Julia?
We just need a way to query from Enzyme_jll what version of libEnzyme is being loaded. 

Something like https://github.com/JuliaParallel/UCX.jl/blob/0fc1600109ae7b947eb8460c82dd8b9c59c93628/src/api.jl#L888

**Comment by wsmoses** [comment]
Sounds good, in any case let's mark this good first issue since the complex stuff is distinct.

All that's needed here is just changing the EnzymeTestUtils skipped tests to match CI

**Comment by vchuravy** [comment]
The EnzymeTestUtils failure on 1.9 and 1.10 seems to be:

```
 [2314] signal (11.1): Segmentation fault
in expression starting at /home/runner/work/Enzyme.jl/Enzyme.jl/lib/EnzymeTestUtils/test/test_reverse.jl:57
_ZNK4llvm24IRBuilderDefaultInserter12InsertHelperEPNS_11InstructionERKNS_5TwineEPNS_10BasicBlockENS_14ilist_iteratorINS_12ilist_detail12node_optionsIS1_Lb0ELb0EvEELb0ELb0EEE at /opt/hostedtoolcache/julia/1.9.4/x64/bin/../lib/julia/libLLVM-14jl.so (unknown line)
Insert<llvm::ExtractValueInst> at /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include/llvm/IR/IRBuilder.h:149 [inlined]
CreateExtractValue at /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include/llvm/IR/IRBuilder.h:2372
cacheForReverse at /workspace/srcdir/Enzyme/enzyme/Enzyme/GradientUtils.cpp:2570
handle_dot at /workspace/srcdir/Enzyme/build/Enzyme/BlasDerivatives.inc:1735
handleBLAS at /workspace/srcdir/Enzyme/build/Enzyme/BlasDerivatives.inc:26
handleKnownCallDerivatives at /workspace/srcdir/Enzyme/enzyme/Enzyme/CallDerivatives.cpp:2254
visitCallInst at /workspace/srcdir/Enzyme/enzyme/Enzyme/AdjointGenerator.h:6223
delegateCallInst at /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include/llvm/IR/InstVisitor.h:302 [inlined]
visitCall at /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include/llvm/IR/Instruction.def:209 [inlined]
visit at /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include/llvm/IR/Instruction.def:209
visit at /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include/llvm/IR/InstVisitor.h:112 [inlined]
CreatePrimalAndGradient at /workspace/srcdir/Enzyme/enzyme/Enzyme/EnzymeLogic.cpp:4372
EnzymeCreatePrimalAndGradient at /workspace/srcdir/Enzyme/enzyme/Enzyme/CApi.cpp:587
EnzymeCreatePrimalAndGradient at /home/runner/work/Enzyme.jl/Enzyme.jl/src/api.jl:154
```

So a segmentation fault in `handleBLAS`

**Comment by wsmoses** [comment]
This is now fixed closing.
