### ISSUE TITLE
Add more details to docs

### ISSUE THREAD

**Issue by gdalle** [EnzymeAD/Enzyme.jl#1355]
In order to be able to merge #1343 with the restructuring that was already done, here's a record of the things we still want to add:

- pointer shenanigans for `Duplicated(x, dx)` with `typeof(x) != typeof(dx)` => https://github.com/EnzymeAD/Enzyme.jl/pull/1343#discussion_r1532933852
- discussion on sparse and structured arrays => https://github.com/EnzymeAD/Enzyme.jl/pull/1343#issuecomment-2013169530 
- GPU and friends => https://github.com/EnzymeAD/Enzyme.jl/pull/1343#discussion_r1532937548

**Comment by wsmoses** [comment]
Closing as PR's have landed
