### ISSUE TITLE
EnzymeTestUtils nondeterminstic failure

### ISSUE THREAD

**Issue by wsmoses** [EnzymeAD/Enzyme.jl#1397]
@sethaxen I'm seeing CI nondeeterminstically fail for EnzymeTestUtils as in https://github.com/EnzymeAD/Enzyme.jl/actions/runs/8767212680/job/24060205716?pr=1371

can we set a seed or something always?

**Comment by sethaxen** [comment]
Yeah, makes sense. IIRC test set always uses the global rng state without modifying it, so setting the seed once before evaluating any tests would fix this.

**Comment by wsmoses** [comment]
I guess there's two things here:
1) presumably we can just set a fixed seed in runtests
2) should we make the test functions take a seed?

**Comment by sethaxen** [comment]
>     2. should we make the test functions take a seed?

We could have the test functions take an `rng`, defaulting to `Random.default_rng()`. I don't really know when someone would want to change the RNG, but at least it would be possible. That's preferable to a seed.
