### ISSUE TITLE
Overly strict enforcement of type equality for Duplicated

### ISSUE THREAD

**Issue by andrinr** [EnzymeAD/Enzyme.jl#1441]
As mentioned in the FAQ: 

_In some ways, type equality is too strict: two different types can have the same data layout. For instance, a vector and a view of a matrix column are arranged identically in memory._

I am rather new to Julia and I might be mistaken, however I am pretty sure that using views in combination of Enzyme are best practice for differentiating explicit forward solvers. Therefore It does not some ideal that we are not allowed to use Views here.

**Comment by wsmoses** [comment]
You can use views. You just must use the same offset view in primal and shadow values (this is checked by the constructor).

**Comment by andrinr** [comment]
But in most cases, the only the primal is a view, while the shadow is not, as we not need to keep track of the entire history of shadow variables.
