### ISSUE TITLE
Julia crash when passing Ref of Mixed activity struct 

### ISSUE THREAD

**Issue by m-bossart** [EnzymeAD/Enzyme.jl#1494]
I have a struct that is passed to the high level function that I am using with `autodiff`. The struct gives a mixed activity warning (as expected). I'm trying to bypass this by passing a reference to the variable instead per the example here: https://docs.sciml.ai/Enzyme/dev/faq/#Mixed-activity

When I run my code Julia crashes with the attached (long) error. I haven't yet been able to reproduce with a MWE but I'm hoping for some help interpreting the error message. 

[mixed_activity_ref_error.txt](https://github.com/user-attachments/files/15569841/mixed_activity_ref_error.txt)

**Comment by vchuravy** [comment]
Please post a MWE

**Comment by wsmoses** [comment]
With the recent mixed activity work landed and no MWE posted, I'm going to go ahead and close this as stale. Please reopen if it persists.
