### ISSUE TITLE
Enzyme API has some wrong argument types.

### ISSUE THREAD

**Issue by jlk9** [EnzymeAD/Enzyme.jl#1578]
The current doc for Enzyme.jl has the argument for both `maxtypedepth!` and `maxtypeoffset!` listed as Bool when they should be int. This can be seen here: [https://enzyme.mit.edu/julia/stable/api/#Enzyme.API.maxtypedepth!-Tuple{Any}](https://enzyme.mit.edu/julia/stable/api/#Enzyme.API.maxtypedepth!-Tuple{Any})

<img width="912" alt="image" src="https://github.com/EnzymeAD/Enzyme.jl/assets/16888623/27fe8362-e411-4c4c-8a55-9e5eb8376157">

**Comment by wsmoses** [comment]
Fixed by https://github.com/EnzymeAD/Enzyme.jl/commit/91083c1ba1592c5ad6805f6eb30e298678670b4c
