### ISSUE TITLE
Inconsistent empty return type

### ISSUE THREAD

**Issue by mhauru** [EnzymeAD/Enzyme.jl#1584]
MWE:
```
using Enzyme

f(x) = 1.0
x = Float64[]

@show Enzyme.gradient(Enzyme.Forward, f, x)
@show Enzyme.gradient(Enzyme.Reverse, f, x)
```

Output:
```
Enzyme.gradient(Enzyme.Forward, f, x) = ()
Enzyme.gradient(Enzyme.Reverse, f, x) = Float64[]
```

The empty tuple throws things off a bit. Other AD packages also return empty arrays of the type of `x`.

**Comment by wsmoses** [comment]
This is expected behavior, so not a bug. In particular a tuple is returned as a consequence of batching over n variables.

It may be worthwhile to change this, but also it may be useful for performance since tuples may be faster in some use cases.

**Comment by wsmoses** [comment]
I'm not oppposed to having it return an array, but I guess I'm not presently understanding the motivation for well enought.

Since tuple's support the same length and indexing operatinos as an array, but also have a compile time known type, would this not be an advantage to keep if we already have it?

**Comment by mhauru** [comment]
Hmm, yeah, thinking about this more, I'm unsure as well. I see your point that knowing the length of the return value at compile time could be a benefit. It's a corner case, but in the above MWE the return type is `Tuple{}` which loses all information about element type, which is what tripped up the Bijectors.jl tests.

**Comment by wsmoses** [comment]
I mean differentiating a zero length array is already weird since there’s no value to return anyways
