### ISSUE TITLE
xlogy grad wrong at 0

### ISSUE THREAD

**Issue by mhauru** [EnzymeAD/Enzyme.jl#1601]
MWE:
```julia
module MWE

using LogExpFunctions: xlogy
using FiniteDifferences
using Enzyme

# function xlogy(x::Number, y::Number)
#     result = x * log(y)
#     return iszero(x) && !isnan(y) ? zero(result) : result
# end

f(x) = xlogy(x[1], 23.0)

x = [0.0]

finitediff = FiniteDifferences.grad(central_fdm(5, 1), f, x)[1]
grad_forward = Enzyme.gradient(Enzyme.Forward, f, x)
grad_reverse = Enzyme.gradient(Enzyme.Reverse, f, x)
@show finitediff
@show grad_forward
@show grad_reverse

end
```
Commented out is the actual body of `xlogy`.

Output:
```
finitediff = [3.1354942159291497]
grad_forward = (0.0,)
grad_reverse = [0.0]
```

The `iszero(x)` throws things off. E.g. ForwardDiff.jl and ReverseDiff.jl deal with this by depending on DiffRules.jl, which defines a rule here: https://github.com/JuliaDiff/DiffRules.jl/blob/8842177391b07dcd8234ac7612b9ca8ca72d28e0/src/rules.jl#L305

Could Enzyme do the same?

**Comment by wsmoses** [comment]
Completed here: https://github.com/EnzymeAD/Enzyme.jl/pull/1615
