### ISSUE TITLE
Gradient in tutorial gives wrong results

### ISSUE THREAD

**Issue by archermarx** [EnzymeAD/Enzyme.jl#1610]
Example from the [Basics](https://enzyme.mit.edu/julia/stable/generated/autodiff/) page in the documentation.

```julia
using Enzyme

begin
  function f0(x, y)
    y[1] = x[1] * x[1] + x[2] * x[1]
  end

  x = [2.0, 2.0]
  bx = [0.0, 0.0]
  y = [0.0]
  by = [1.0]

  Enzyme.autodiff(Enzyme.Reverse, f0, Duplicated(x, bx), Duplicated(y, by))

  g = copy(bx)
  @show g
end
```

This gives
```
g = [12.0, 4.0]
```

which is twice the expected value reported in the tutorial. Changing `by` to `[0.0]` gives the expected answer, which contradicts the text of the tutorial.

I'm on Julia 1.10.4 on x86-64 using Enzyme 0.12.21.

**Comment by wsmoses** [comment]
I don't follow here, can you show the wrong answer setup?

**Comment by archermarx** [comment]
How do you mean? I get the wrong answer stored in `bx` by running the above code, which is more or less copy-pasted directly from the docs

https://enzyme.mit.edu/julia/stable/generated/autodiff/

More concretely, the function is f(x) = x1^2 + x1 x2. The gradient of this function is (2 x1 + x2, x1), which, evaluated at (2, 2) should give (6, 2). In the tutorial, running the code above should store `[6.0, 2.0]` in `bx`. However, I get `[12.0, 4.0]`, which is twice the expected answer.

**Comment by archermarx** [comment]
Ok, never mind. I omitted the `return nothing` in the function signature by accident, which changed the result.
