### ISSUE TITLE
doc: Got confused with `EnzymeCore.Duplicated` doc

### ISSUE THREAD

**Issue by hz-xiaxz** [EnzymeAD/Enzyme.jl#1624]
In the [doc](https://github.com/EnzymeAD/Enzyme.jl/blob/40fe290d9589a1125101d38e8dd6a558f183fc5b/lib/EnzymeCore/src/EnzymeCore.jl#L55-L62), should the second parameter be `dx` instead of `∂f_∂x`? If not so, what does the `dx` refer to in the docstring? I'm entirely new to AD and if I asked a silly question, please feel free to tell me so!

**Comment by mcabbott** [comment]
Yes, I believe `dx` and `∂f_∂x` mean the same thing there. Ideally the docstring would use `∂f_∂x` everywhere.

**Comment by hz-xiaxz** [comment]
thanks
