### ISSUE TITLE
"UndefVarError: `N` not defined" when writing custom rule

### ISSUE THREAD

**Issue by danielwe** [EnzymeAD/Enzyme.jl#1630]
Stumbled into this line when experimenting with custom rules and got an UndefVarError:

https://github.com/EnzymeAD/Enzyme.jl/blob/c83fcf8960abfba435752dba318a883da4d752c6/src/rules/customrules.jl#L234

There's no `N` defined in the scope of this function. Looks like the issue also occurs on this line:

https://github.com/EnzymeAD/Enzyme.jl/blob/c83fcf8960abfba435752dba318a883da4d752c6/src/rules/customrules.jl#L1038

**Comment by wsmoses** [comment]
Oh yeah that should presumably just be width.

Open a PR?
