### ISSUE TITLE
Raise Julia errors rather than crashing on Assertion failures

### ISSUE THREAD

**Issue by mhauru** [EnzymeAD/Enzyme.jl#1634]
As discussed in https://github.com/TuringLang/Bijectors.jl/pull/318, in cases like https://github.com/TuringLang/Bijectors.jl/actions/runs/9871431348/job/27259337160?pr=318 (`Assertion 'unwrapMode != UnwrapMode::LegalFullUnwrap' failed.`) it would be preferable to raise a Julia error rather than abort.

**Comment by wsmoses** [comment]
This is an issue that requires doing so at each assertion and can't easily be changed to generally forward to Julia. I'm going to close this and recommend a new issue be opened for each specific assertion which is hit and not throwing a Julia level error
