### ISSUE TITLE
Does Enzyme's high-level API assume `f` is constant?

### ISSUE THREAD

**Issue by gdalle** [EnzymeAD/Enzyme.jl#1670]
Still in the context of https://github.com/gdalle/DifferentiationInterface.jl/pull/375, wanted to know if I can use `gradient`, `jacobian` and the like

**Comment by wsmoses** [comment]
It does, though we can add a duplicated wrapper if desired.

Happy to take a PR for this

**Comment by wsmoses** [comment]
Closing as answered, feel free to open a PR to extend.
