### ISSUE TITLE
Unexpected zero derivative

### ISSUE THREAD

**Issue by swilliamson7** [EnzymeAD/Enzyme.jl#1690]
As the title says, I'm getting a zero derivative when I wouldn't expect to. It seems to have something to do with an `if` statement, but that's my best guess. The specific script to run [is here](https://github.com/swilliamson7/ShallowWaters.jl/blob/zannabolton/zero_derivative_bug/zero_derivative.jl), part of my ShallowWaters.jl fork (https://github.com/swilliamson7/ShallowWaters.jl/tree/zannabolton). 

The lines of interest are https://github.com/swilliamson7/ShallowWaters.jl/blob/f5eeb84f724e17a9d96f2566cfba6ed1fa6a0aee/zero_derivative_bug/zero_derivative.jl#L191-L208, this is where I compute the actual loss function. I'm more than happy to meet/chat/provide further explanation with regards to any of this code, since I know it's not minimized so please let me know!

**Comment by wsmoses** [comment]
Just for fun, without checkpointing is it zero?

**Comment by swilliamson7** [comment]
I removed checkpointing and now get "ERROR: LoadError: Enzyme compilation failed due to illegal type analysis." The text file for the bug is in the same repo as above, [here](https://github.com/swilliamson7/ShallowWaters.jl/tree/zannabolton/zero_derivative_bug)

**Comment by wsmoses** [comment]
interestingly from the log it looks like something checkpointing related is still being called?

```

val:   %399 = addrspacecast {} addrspace(10)* %ptr_phi to i8 addrspace(11)*, !dbg !119 origin=  %399 = addrspacecast {} addrspace(10)* %ptr_phi to i8 addrspace(11)*, !dbg !119
MethodInstance for loop(::Main.ShallowWaters.ModelSetup{Float32, Float32}, ::Revolve{Main.ShallowWaters.ModelSetup})
```

isn't revolve checkpointing?

**Comment by wsmoses** [comment]
from


Stacktrace:
 [1] loop
   @ ~/Documents/GitHub/ShallowWaters_work/ShallowWaters.jl/zero_derivative_bug/zero_derivative.jl:77

**Comment by wsmoses** [comment]
in any case some minimization would also be helpful here

**Comment by swilliamson7** [comment]
starting to minimize this/make sure I can reproduce it (mostly writing here to keep me accountable and let you know I'm working on it lol)

**Comment by swilliamson7** [comment]
Okay, coming back to this it's definitely still a weird bug. The script I run is [here](https://github.com/swilliamson7/ShallowWaters.jl/blob/zannabolton/zero_derivative_bug/zero_derivative.jl), and I'm not quite getting zero as my derivatives but rather something that looks like this: 

```julia
julia> dS.Prog.u
131×132 Matrix{Float32}:
 0.0  0.0     0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0    …     0.0       0.0       0.0      0.0      0.0      0.0       0.0       0.0    0.0  0.0
 0.0  0.0   507.138   507.139   507.139   507.139   507.139   507.139   507.139   507.138   507.138      506.911   506.911   506.91   506.91   506.91   506.909   506.908   506.908  0.0  0.0
 0.0  0.0     0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0          0.0       0.0       0.0      0.0      0.0      0.0       0.0       0.0    0.0  0.0
 0.0  0.0     0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0          0.0       0.0       0.0      0.0      0.0      0.0       0.0       0.0    0.0  0.0
 0.0  0.0     0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0          0.0       0.0       0.0      0.0      0.0      0.0       0.0       0.0    0.0  0.0
 0.0  0.0     0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0    …     0.0       0.0       0.0      0.0      0.0      0.0       0.0       0.0    0.0  0.0
 0.0  0.0     0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0          0.0       0.0       0.0      0.0      0.0      0.0       0.0       0.0    0.0  0.0
 0.0  0.0     0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0          0.0       0.0       0.0      0.0      0.0      0.0       0.0       0.0    0.0  0.0
 ⋮                                          ⋮                                                 ⋮      ⋱                                  ⋮                                            ⋮    
 0.0  0.0     0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0          0.0       0.0       0.0      0.0      0.0      0.0       0.0       0.0    0.0  0.0
 0.0  0.0     0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0          0.0       0.0       0.0      0.0      0.0      0.0       0.0       0.0    0.0  0.0
 0.0  0.0     0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0    …     0.0       0.0       0.0      0.0      0.0      0.0       0.0       0.0    0.0  0.0
 0.0  0.0     0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0          0.0       0.0       0.0      0.0      0.0      0.0       0.0       0.0    0.0  0.0
 0.0  0.0     0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0          0.0       0.0       0.0      0.0      0.0      0.0       0.0       0.0    0.0  0.0
 0.0  0.0     0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0          0.0       0.0       0.0      0.0      0.0      0.0       0.0       0.0    0.0  0.0
 0.0  0.0  -506.949  -506.95   -506.95   -506.95   -506.951  -506.951  -506.951  -506.951  -506.952     -506.98   -506.98   -506.98  -506.98  -506.98  -506.98   -506.98   -506.98   0.0  0.0
 0.0  0.0     0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0    …     0.0       0.0       0.0      0.0      0.0      0.0       0.0       0.0    0.0  0.0

```
which is extra weird, and I'm 99% sure the derivative shouldn't look like this. The cost function computation that generates this derivative is computed in [these lines](https://github.com/swilliamson7/ShallowWaters.jl/blob/7adb862a912535f4368f44c50e246038c3b5614a/zero_derivative_bug/zero_derivative.jl#L141-L158). If I instead compute derivatives of say, one of the state fields I get correct results and everything works. This can be done by changing [this line](https://github.com/swilliamson7/ShallowWaters.jl/blob/7adb862a912535f4368f44c50e246038c3b5614a/zero_derivative_bug/zero_derivative.jl#L69) to say, `return S.Prog.u[50,50]`. 

I did try to minimize, and managed to get rid of some lines, but I need _something_ to modify my states and proceed the integration, because otherwise the cost function is zero and then the derivative is just zero. So what I found would happen is I'd remove a line of code and suddenly the integration doesn't happen and everything is, understandably, zero :/ 

Anyways, meeting to show this and explain it might be easiest, I'm also happy to provide any other comments/information that you need!

**Comment by swilliamson7** [comment]
I forgot to mention, rather importantly, that this is without Checkpointing and runs! Previously removing checkpointing led to some Enzyme errors. Basically now it's just that Enzyme seems to be doing something weird with the derivative calculation

**Comment by wsmoses** [comment]
With a bunch more fixes added since, does this still err?

**Comment by swilliamson7** [comment]
This no longer errors I think, so closing it. I believe it was also more related to Checkpointing than Enzyme
