### ISSUE TITLE
Seemingly wrong derivative 

### ISSUE THREAD

**Issue by swilliamson7** [EnzymeAD/Enzyme.jl#1691]
Now moving to a different error with essentially the same code as in https://github.com/EnzymeAD/Enzyme.jl/issues/1690. I've "corrected" the derivative issue in #1690, but now the derivative just seems wrong. The script to run is [this one](https://github.com/swilliamson7/ShallowWaters.jl/blob/zannabolton/wrong_derivative_bug/wrong_derivative.jl). The new way I compute my loss function, when comparing to #1690, is in [these lines](https://github.com/swilliamson7/ShallowWaters.jl/blob/f5eeb84f724e17a9d96f2566cfba6ed1fa6a0aee/wrong_derivative_bug/wrong_derivative.jl#L191-L228), in the same repo as the other issue. I essentially moved 

```julia 
            temp = ShallowWaters.PrognosticVars{Float32}(ShallowWaters.remove_halo(S.Prog.u,
            S.Prog.v,
            S.Prog.η,
            S.Prog.sst,S)...)

            eta_avg = eta_avg .+ temp.η
```

to inside the `if` statement, as well as adding an `else` to make sure my average is continued even if there is no artificial data. In the code I consider the derivative in `dS.Prog.u[40,40]` and compare this value when computed first with Enzyme and then with finite differences. The Enzyme value comes out to be 

```julia 
julia> enzyme_deriv
-0.0039309226f0
```

and then the result from finite differences is 

```julia
julia> diffs
13-element Vector{Any}:
   -0.04697383219866424
   -0.04684719766421495
   -0.04672145273281482
   -0.04659525717336237
    ⋮
   -3.0102531582087972
  -20.317679172876524
 -252.77864097006386
```

I checked other entries in `dS.Prog.u` and they all seemed to be mismatched. I've tried to be sure that this isn't happening because I missed something/checked my derivative incorrectly, but it's always possible that I missed something! Also, like before, this code isn't minimized and I'm more than happy to provide further explanation/help/discussion if there's anything else you need to look at this!

**Comment by wsmoses** [comment]
Yeah I think probably a reduction here would be useful to dissect.

**Comment by wsmoses** [comment]
also same comment of what happens without checkpointing.jl?

**Comment by swilliamson7** [comment]
Without checkpointing the derivative matches! What does this mean is going on?

**Comment by wsmoses** [comment]
Not sure, but it feels like there's a bug in check pointing. Reopen on
check pointing.jl and ping Michel?

**Comment by swilliamson7** [comment]
Sounds good, we can probably close this then?
