### ISSUE TITLE
recent jacobian changes break StaticArrays

### ISSUE THREAD

**Issue by ExpandingMan** [EnzymeAD/Enzyme.jl#1714]
The recent changes from [this commit](https://github.com/EnzymeAD/Enzyme.jl/commit/2b681d54234190fdcf70b2844af8cd33700ee0be) are causing `jacobian` to allocate and return `Array` objects even when passed `SArray`
```julia
◖◗ x = @SVector ones(4);

◖◗ Enzyme.jacobian(Forward, ξ -> 2 * ξ, x)
4×4 Matrix{Float64}:
 2.0  0.0  0.0  0.0
 0.0  2.0  0.0  0.0
 0.0  0.0  2.0  0.0
 0.0  0.0  0.0  2.0
```

Not really sure what cases this change was meant to handle, so it's not clear to me how this would be fixed.  I'm currently doing the following to get the jacobian with values
```julia
function enz_val_jacobian(𝒻, x; shadow=Enzyme.onehot(x))
    (val, cols) = if length(shadow) == 0
        ()
    else
        Enzyme.autodiff(Forward, 𝒻, BatchDuplicated, BatchDuplicated(x, shadow))
    end
    # adapted from Enzyme.jl; note this broke in 0.12.28
    (val, reduce(hcat, cols))
end
```

**Update:** Pretty sure staticarrays is missing methods for `Base.stack`, not completely certain that's the entire problem here.

**Comment by wsmoses** [comment]
Yeah I think that's the issue at hand (which should be made on staticarrays).

The change specifically corrected handling of multidimensional outputs/inputs

**Comment by wsmoses** [comment]
should be fixed presently on main
