### ISSUE TITLE
Query for Enzyme compatibility without running the code

### ISSUE THREAD

**Issue by ChrisRackauckas** [EnzymeAD/Enzyme.jl#178]
In DiffEq we're doing a bit of:

```julia
try
      Enzyme.autodiff(Enzyme.Duplicated(du, du),
                      u0,p,prob.tspan[1]) do out,u,_p,t
        prob.f(out, u, _p, t)
        nothing
      end
      true
    catch
      false
    end
```

to see whether Enzyme is compatible with a given function, but it would be nice to be able to do this without actually calling the function.

**Comment by vchuravy** [comment]
Yeah, @wsmoses minimum improvement here is not to assert, but to report a catch-able error.

**Comment by wsmoses** [comment]
https://github.com/wsmoses/Enzyme/pull/438 This should start to enable julia errors rather than having to use llvm unreachable/assertions.

**Comment by wsmoses** [comment]
@ChrisRackauckas once https://github.com/wsmoses/Enzyme.jl/pull/193 lands (with corresponding jll bump) the BLAS (and other errors) should come through as proper julia errors, rather than LLVM assertions.

**Comment by ChrisRackauckas** [comment]
And then how hard is it to do the next step of compiling and throwing an error if the program would through an error, but not requiring the computation?

**Comment by vchuravy** [comment]
Closing this since our stance is to give a runtime error where ever possible. Please open individual issues for things that remain compile-time errors.
