### ISSUE TITLE
`BatchDuplicated` on functions

### ISSUE THREAD

**Issue by gdalle** [EnzymeAD/Enzyme.jl#1783]
I’m using Enzyme to differentiate through a closure, and `BatchDuplicated` on the closure itself doesn’t seem to work, unlike `Duplicated`.

```julia
using Enzyme

struct MyClosure{A}
    a::A
end

function (mc::MyClosure)(x)
    # computes x^2 using internal storage
    mc.a[1] = x
    return mc.a[1]^2
end

g = MyClosure([0.0])
g(3.0)  # 9.0

g_and_dg = Duplicated(g, make_zero(g))
x_and_dx = Duplicated(3.0, 5.0)
autodiff(Forward, g_and_dg, Duplicated, x_and_dx)  # (9.0, 30.0)

g_and_dgs = BatchDuplicated(g, (make_zero(g), make_zero(g)))
x_and_dxs = BatchDuplicated(3.0, (5.0, 7.0))
autodiff(Forward, g_and_dgs, BatchDuplicated, x_and_dxs)  # error
```

The last call triggers the following error:

```julia
ERROR: TypeError: in ccall argument 3, expected MyClosure{Vector{Float64}}, got a value of type Tuple{MyClosure{Vector{Float64}}, MyClosure{Vector{Float64}}}
Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/Enzyme/Tb3Iu/src/compiler.jl:7151 [inlined]
 [2] enzyme_call
   @ ~/.julia/packages/Enzyme/Tb3Iu/src/compiler.jl:6760 [inlined]
 [3] ForwardModeThunk
   @ ~/.julia/packages/Enzyme/Tb3Iu/src/compiler.jl:6640 [inlined]
 [4] autodiff(::ForwardMode{…}, f::BatchDuplicated{…}, ::Type{…}, args::BatchDuplicated{…})
   @ Enzyme ~/.julia/packages/Enzyme/Tb3Iu/src/Enzyme.jl:437
 [5] top-level scope
Some type information was truncated. Use `show(err)` to see complete types.
```

**Comment by gdalle** [comment]
I encountered this issue during PR https://github.com/gdalle/DifferentiationInterface.jl/pull/446

Perhaps it also explains the Julia crash observed in this PR run: https://github.com/gdalle/DifferentiationInterface.jl/actions/runs/10687930979/job/29626626888?pr=446
For context, this happened during a forward-over-forward HVP

**Comment by wsmoses** [comment]
other crash is likely unrelated, please open another issue with a MWE for
that as well!

**Comment by gdalle** [comment]
Thanks, I'll do my best.
As we had discussed, the idea is to use `BatchDuplicated` by default in DI since I now natively rely on batch mode for Jacobians and Hessians. We might encounter more uncharted waters.

**Comment by wsmoses** [comment]
Resolved by https://github.com/EnzymeAD/Enzyme.jl/pull/1784
