### ISSUE TITLE
Error: "task switch not allowed from inside staged nor pure functions"

### ISSUE THREAD

**Issue by gdalle** [EnzymeAD/Enzyme.jl#1804]
This new error appeared today in the DI tests, for an unrelated docs PR. I had tests passing with Enzyme v0.12.36 before, so how can the behavior have changed without a new version?
Guilty CI log: https://github.com/gdalle/DifferentiationInterface.jl/actions/runs/10805706418/job/29973227815

**Comment by wsmoses** [comment]
I think LLVM.jl had a release which created the depwarns

**Comment by wsmoses** [comment]
Dup of https://github.com/EnzymeAD/Enzyme.jl/issues/1808
