### ISSUE TITLE
Move runtime activity into mode parameter

### ISSUE THREAD

**Issue by wsmoses** [EnzymeAD/Enzyme.jl#1810]
While we're doing a breaking release, what are folks thoughts -- specifically @vchuravy 

For now we still will have to do an Enzyme.API.runtimeActivity!(true/false) inside at the start of the generated function, until the Enzyme API for changes.

We'll also probably need some way to query this in gutils, and also pass this as a config to rules.

Which means all rules need a config now [not just forward], which is breaking for fwd mode rules in the ecosystem.

**Comment by wsmoses** [comment]
We can arguably forgo the rules change for now, but it is a bit suss presently regardless.

**Comment by vchuravy** [comment]
Yeah I was thinking this the other day as well
