### ISSUE TITLE
Readme image is broken

### ISSUE THREAD

**Issue by gdalle** [EnzymeAD/Enzyme.jl#1846]

**Comment by wsmoses** [comment]
Looks fine to me?

<img width="1255" alt="Screenshot 2024-09-17 at 11 17 23 AM" src="https://github.com/user-attachments/assets/c2b41757-9032-4d16-857a-85c4c24a3619">

**Comment by wsmoses** [comment]
do you have anything showing it going awry?

**Comment by gdalle** [comment]
It wasn't loading earlier but it is now, sorry. Maybe a GitHub server delay or sth

**Comment by gdalle** [comment]
It's broken on JuliaHub at the very least. Perhaps it depends on the navigator?

![image](https://github.com/user-attachments/assets/aa9c5059-3679-440c-91c1-a23a5fe61ffc)

**Comment by wsmoses** [comment]
yeah not sure if there's anything that can be done here
