### ISSUE TITLE
List breaking changes for v0.13?

### ISSUE THREAD

**Issue by gdalle** [EnzymeAD/Enzyme.jl#1861]
Hi, well done on the new release!
Would it be possible to list the major breaking changes somewhere?

**Comment by wsmoses** [comment]
Yup we will make an announcement once we’ve done the sweep to help various ecosystem deps.

**Comment by gdalle** [comment]
I don't know about the other deps but if you want DI to update I kinda need to know the breaking changes first ^^

**Comment by gdalle** [comment]
Especially since most of the PRs have no description whatsoever

**Comment by ExpandingMan** [comment]
Not sure if you were suggesting waiting for dependencies to update, but the dependencies themselves are of course the things that are most in need of a detailed list of breaking changes.

**Comment by wsmoses** [comment]
yeah but first I need to fix the fact that GPU tests rn result in a circular dependency between Enzyme <-> CUDA <-> KernelAbstractions, so neither can successfully run tests presently, so there might be some minor changes as these get mutually re-compatible again

=> I wouldn't consider this officially released [tho it is practically ATM for the sake of fixing related nonsense], until that's resolved

**Comment by wsmoses** [comment]
I mean if you want to, go for it, but the details should hopefully be
resolved in the next day or two so I personally wouldn’t bother

**Comment by gdalle** [comment]
Fair enough. I'll try to update DI and see what breaks there too
