### ISSUE TITLE
passing `n_outs` keyword arg changes reverse mode jacobian output type

### ISSUE THREAD

**Issue by ExpandingMan** [EnzymeAD/Enzyme.jl#1863]
```julia
julia> x = ones(2);

julia> f2(x) = [x[1], 2*x[2]];

julia> Enzyme.jacobian(ReverseWithPrimal, f2, x, n_outs=Val(2))
(derivs = [1.0 0.0; 0.0 2.0], val = [1.0, 2.0])

julia> Enzyme.jacobian(ReverseWithPrimal, f2, x)
(derivs = ([1.0 0.0; 0.0 2.0],), val = [1.0, 2.0])
```

The `derivs` should be always nested to be consistent.

**Comment by wsmoses** [comment]
This is expected as n_outs must contain the shape of the outputs (and here you pass 2 instead of (2,)). 

Certainly a better error is warranted, but this is nevertheless undefined behavior to use it in this way

**Comment by ExpandingMan** [comment]
Oh, I hadn't realized how that worked.  Yeah, at the very least this could use a clear warning, I don't think I would have guessed that the value includes the shape of the wrapping tuple (if I'm even understanding this correctly...).

**Comment by wsmoses** [comment]
no it's not the shape of the wrapping tuple, its size(f2(x))

**Comment by ExpandingMan** [comment]
That makes sense, but shouldn't it throw an error then if it just gets an integer?

**Comment by wsmoses** [comment]
resovled by https://github.com/EnzymeAD/Enzyme.jl/pull/1864
