### ISSUE TITLE
Zero gradient regression involving global variables

### ISSUE THREAD

**Issue by tscode** [EnzymeAD/Enzyme.jl#1882]
I was just bitten by what I hope is a version of this boiled-down example:
```julia
using Enzyme

myfunction(a, b) = sum(abs2, a) + b

b = 5

f = p -> myfunction(p, b)
g = p -> myfunction(p, 5)

@show gradient(Reverse, f, [1., 0.]) # works
@show gradient(Reverse, g, [1., 0.]) # works

@show gradient(Reverse, f, (1., 0.)) # does not work
@show gradient(Reverse, g, (1., 0.)) # works
```

Comments:
- I use the official `1.10.4` julia binary via rustup on Arch Linux.
- I observed this behavior for `Enzyme 0.13.1` and the current `main`. With version `0.12.36` it worked as expected.
- The same also happens with `SVector` from `StaticArrays` instead of tuples.
- Declaring `b` constant resolves the problem.
- Unrelated: Where is the best place to ask about Enzyme performance? (I have a relatively simple function that takes ~50ns without allocations, but whose gradient (4 components) takes about 100 times longer and has dozens of allocations. Is this expected?)

**Comment by wsmoses** [comment]
works on main
