### ISSUE TITLE
What is the use of `DuplicatedNoNeed` now that `ReturnPrimal` is in the mode?

### ISSUE THREAD

**Issue by gdalle** [EnzymeAD/Enzyme.jl#1892]
Is it just redundant information? If so, which one takes precedence?

**Comment by wsmoses** [comment]
See docs https://enzyme.mit.edu/julia/stable/api/#EnzymeCore.DuplicatedNoNeed it now exclusively is for arguments.

**Comment by gdalle** [comment]
Thanks for the pointer but the docstring is still unclear to me. What would be the purpose of a variable to which we write but from which we never read again?

**Comment by wsmoses** [comment]
this help? https://github.com/EnzymeAD/Enzyme.jl/pull/1904
