### ISSUE TITLE
Incorrect derivatives of randn()

### ISSUE THREAD

**Issue by Jinyu95** [EnzymeAD/Enzyme.jl#1902]
Hello, I am using Enzyme 0.13.3 on Julia 1.10.4. When I try to calculate with the randn() function, some of the derivatives become NaN, which never happened when I was using the old version of Enzyme, e.g., 0.12.12.

```julia
using Enzyme, Random
function f(L)
    Pts = randn(1000)
    return Pts * L
end

g = autodiff(ForwardWithPrimal, f, Duplicated(1.0, 1.0))
```

The results are,
`(var"1" = [-1.291503755343439, 1.338538415903224, -0.8453583823362729, 0.22304028858797614, NaN, 0.07499515167553646, 1.3437396172304426, 1.030860320072257, NaN, 0.009625274141182433  …  NaN, 0.0015532653551571462, NaN, 0.8239779015560049, -0.8827069305850216, -0.8040953683939528, NaN, 0.40769081041334093, NaN, -0.4926716859105508], var"2" = [-1.291503755343439, 1.338538415903224, -0.8453583823362729, 0.22304028858797614, 0.21742228694385105, 0.07499515167553646, 1.3437396172304426, 1.030860320072257, 0.8129765853808152, 0.009625274141182433  …  -1.2329602926216028, 0.0015532653551571462, -0.5951276129217884, 0.8239779015560049, -0.8827069305850216, -0.8040953683939528, 1.723594446839804, 0.40769081041334093, -0.8332815626433686, -0.4926716859105508])`

**Comment by wsmoses** [comment]
Fixed by https://github.com/EnzymeAD/Enzyme.jl/pull/1906
