### ISSUE TITLE
Utilities to translate from `ReverseMode` to `ReverseModeSplit`

### ISSUE THREAD

**Issue by gdalle** [EnzymeAD/Enzyme.jl#1938]
In DI, the `pullback` functions use split reverse mode by default, so they disregard the `mode` field of `AutoEnzyme` (because I figure no one is going to pass a `ReverseSplitWithPrimal` anyway). But still I'd like to respect some of the attributes of the `ReverseMode` that the user provides.
Would you welcome a PR with functions that translate a `ReverseMode` to the corresponding `ReverseModeSplit`, setting reasonable defaults for the remaining type parameters?

**Comment by wsmoses** [comment]
Sure!

**Comment by wsmoses** [comment]
Though you should still check the mode in case they do

**Comment by gdalle** [comment]
Then I'd also need translation in the other direction, in case they pass me a split mode but I just wanna do gradient

**Comment by wsmoses** [comment]
Also sure if you want
