### ISSUE TITLE
`const global` ref seems to be internalized during compilation

### ISSUE THREAD

**Issue by vchuravy** [EnzymeAD/Enzyme.jl#203]

**Comment by vchuravy** [comment]
```
julia> using Enzyme

julia> const A = zeros(3,3)
3×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

julia> f() = A[1]
f (generic function with 1 method)

julia> Enzyme.fwddiff(f)
(0.0,)

julia> A[1] = 2.0
2.0

julia> Enzyme.fwddiff(f)
(0.0,)
```

**Comment by vchuravy** [comment]
@maleadt do you recall if GPUCompiler is doing anything special or is this more a case of `jl_create_native` embedding the GVar? (Haven't looked deeply at this.)

**Comment by maleadt** [comment]
We don't do anything special with globals. Which is a shame, because users quickly run into issues internalizing CPU references in GPU code (e.g. https://github.com/JuliaGPU/CUDA.jl/issues/1423).

**Comment by vchuravy** [comment]
Yeah I can't reproduce the case I was thinking of, and I thought we did something we const state, but no that is all inference.
