### ISSUE TITLE
`active_reg_inner` returns `DupState` for immutable struct with untyped field

### ISSUE THREAD

**Issue by danielwe** [EnzymeAD/Enzyme.jl#2039]
Consider this:

```julia-repl
julia> struct Foo
           x
       end

julia> Enzyme.Compiler.active_reg_inner(Foo, (), nothing)
DupState::ActivityState = 2

julia> Enzyme.Compiler.active_reg_inner(Foo, (), nothing, Val(true))  # justActive
AnyState::ActivityState = 0
```

The way I've understood it, `DupState` implies that all differentiable values reachable from an object can be mutated, i.e., that there's some mutable container along the chain of references from the object to each differentiable value. But this isn't known from the type of `Foo`. The simplest counterexample is `Foo(1.0)`. Then again, it could be true, like in `Foo([1.0])`. Wouldn't the appropriate return here be `MixedState`, signaling that you should be prepared for both mutable and immutable values?

**Comment by wsmoses** [comment]
No because the float variable must be boxed (and thus duplicated)

**Comment by wsmoses** [comment]
No because the float variable must be boxed (and thus duplicated)

**Comment by danielwe** [comment]
Quick follow-up if you can spare another second, just to help my understanding:

I get that the value is held in a box, so you can mutate instances of `Foo` from the LLVM side or with some Ref/pointer shenanigans. But Julia seems to go to great lengths to hide this implementation detail, to the point where `Foo(1.0) === Foo(1.0)` is true. Doesn't this imply that mutating the boxed value would violate compiler assumptions and could wreak havoc, say if you do reverse mode autodiff with a `Duplicated(Foo(0.0), Foo(0.0))` argument?

Anyway, I notice that this doesn't currently work, even with `mutable struct Foo; x; end` and/or putting the `Foo(0.0)` in a single-element vector, so perhaps the answer is simply that untyped fields aren't compatible with Enzyme?

**Comment by danielwe** [comment]
For future googlers: `active_reg_inner` actually takes a parameter `::Val{ActiveIsMixed}` as the last argument for when the behavior requested in the OP is desired.
