### ISSUE TITLE
`IO` is not guaranteed const

### ISSUE THREAD

**Issue by danielwe** [EnzymeAD/Enzyme.jl#2091]
More specifically, `active_reg_inner(::IO, ...) != AnyState`. This breaks `make_zero` on objects that hold an `IO` for printing/logging, ref slack thread. MWE:

```julia-repl
julia> using Enzyme

julia> struct Foo{F}
           x::Vector{Float64}
           callback::F
           function Foo(x, io)
               callback() = println(io, "hello")
               return new{typeof(callback)}(x, callback)
           end
       end

julia> foo = Foo([1.0, 2.0, 3.0], stdout)
Foo{var"#callback#1"{Base.TTY}}([1.0, 2.0, 3.0], var"#callback#1"{Base.TTY}(Base.TTY(RawFD(15) open, 0 bytes waiting)))

julia> make_zero(foo)
ERROR: ConcurrencyViolationError("setfield!: atomic field cannot be written non-atomically")
Stacktrace:
 [1] make_zero(::Type{ReentrantLock}, seen::IdDict{Any, Any}, prev::ReentrantLock, ::Val{false})
   @ Enzyme.Compiler ~/.julia/packages/Enzyme/RvNgp/src/make_zero.jl:229
 [2] make_zero
   @ ~/.julia/packages/Enzyme/RvNgp/src/make_zero.jl:225 [inlined]
 [3] make_zero (repeats 2 times)
   @ ~/.julia/packages/Enzyme/RvNgp/src/make_zero.jl:244 [inlined]
 [4] make_zero
   @ ~/.julia/packages/EnzymeCore/w3ILx/src/EnzymeCore.jl:526 [inlined]
 [5] make_zero(prev::Foo{var"#callback#1"{Base.TTY}})
   @ EnzymeCore ~/.julia/packages/EnzymeCore/w3ILx/src/EnzymeCore.jl:526
 [6] top-level scope
   @ REPL[6]:1
```

**Comment by danielwe** [comment]
Is the appropriate solution to add a method `EnzymeRules.inactive_type(::Type{T}) where {T<:IO} = true` here: https://github.com/EnzymeAD/Enzyme.jl/blob/75e6725c07e46352df774904c7289f45e37d6d33/src/internal_rules.jl#L122-L132? Or should `IO` be known const at some lower level within `compiler.jl`?

**Comment by wsmoses** [comment]
yeah thats fine

**Comment by danielwe** [comment]
PR coming up. But while I'm at it, curious about line 126 marking `Type{Function}` as inactive.

1. `Function` is an abstract type, unlike every other type on that list
2. It's common to subtype `Function` for callable structs that contain differentiable data, so fields/arrays typed as `Function` are likely to contain active values.

Should this line be removed?

**Comment by wsmoses** [comment]
So I believe that code should just apply to a literal function and not a subtype/closure

**Comment by danielwe** [comment]
Hm, since it's abstract I would think it only applies when inspecting a type with non-concrete field types/eltypes. The actual type of a literal function `f` is `typeof(f)`, which is a subtype of function but isn't `Function`.

**Comment by danielwe** [comment]
This isn't good, is it? I could easily put a closure or callable struct with lots of differentiable data inside `FunctionWrapper`.

```julia
julia> using Enzyme

julia> struct FunctionWrapper
           f::Function
       end

julia> Enzyme.Compiler.guaranteed_const_nongen(FunctionWrapper, nothing)
true
```

**Comment by wsmoses** [comment]
Can you show an example where that stores a closure?

If Function only represents literal functions and can’t hold a closure it ought be fine, but I see what you’re saying.

**Comment by wsmoses** [comment]
But yeah my first argument above was totally wrong, if function is an abstract type it shouldn’t be there. If it only represents Julia literals it’s okay

**Comment by wsmoses** [comment]
Okay yeah remove that.

We need to figure out something for Julia literals though.

**Comment by danielwe** [comment]
I'm wondering if what you want is even encoded in/derivable from the type? I may define a function with only non-closure methods now, but add a method that captures a variable later. The type doesn't change.

```julia-repl
julia> f(x) = x^2 - 3
f (generic function with 1 method)

# later...
julia> f(x::Float32) = x^2 - a  # a is some global variable
f (generic function with 2 methods)
```

**Comment by wsmoses** [comment]
So there was a reason why historically we had it (something else breaking), but that was even before we made the inactive_type function itself.

Feel free to open a Pr and let’s see what, if anything, breaks

**Comment by wsmoses** [comment]
So in your latter case the function is constant and it doesn’t capture a variable, it references a global variable . E.g sizeof(f) == 0, presumably

**Comment by danielwe** [comment]
Yeah, I'm noticing that capturing locals vs. globals is very different. When capturing locals the function type is literally a callable struct with a gensymmed name, so one can check, e.g., `fieldcount(T) == 0` to see if something was captured or not.

So a reference to a global isn't considered differentiable data, even if the global is a non-const active type?
