### ISSUE TITLE
Illegal updateAnalysis prev:{[-1]:Integer} new: {[-1]:Pointer}

### ISSUE THREAD

**Issue by mmorligh** [EnzymeAD/Enzyme.jl#212]
Hi Valentin

Here is the log of dJUICE running with enzyme: https://gist.github.com/mmorligh/ff5bc981e82920791c98ebc07cf47ce3 
Thanks!
Mathieu

**Comment by wsmoses** [comment]
This looks like us not yet handling union type returns (in essence we're marking the return as [-1]:Pointer, when in reality the LLVM type is `{ {} addrspace(10)*, i8 }`

Can you provide the input code?

**Comment by mmorligh** [comment]
Hi William, thanks a lot for looking into this! The code is available here: https://github.com/DJ4Earth/dJUICE/ you can go to tests/ and run testad.jl. I am quite new to Julia so I apologize in advance if you see anything stupid... 
Many thanks
Mathieu

**Comment by wsmoses** [comment]
Is it not possible to remove the remaining union?

**Comment by mmorligh** [comment]
It is possible but is there an "easy way" to find out where they are in the code?

**Comment by vchuravy** [comment]
The best thing would be if @aviatesk's JET.jl would be able to detect functions that return `Union{,Float64}`.

**Comment by aviatesk** [comment]
Interesting, I will work on integrating such analysis within Enzyme's compilation pass this week.

**Comment by mmorligh** [comment]
Hi @aviatesk, any update on this?

**Comment by aviatesk** [comment]
https://github.com/EnzymeAD/Enzyme.jl/pull/261

**Comment by vchuravy** [comment]
We have several independent issues tracking this. Support union fully will be hard, but we now give much better errors in that case #263
