### ISSUE TITLE
Instruction does not dominate all uses

### ISSUE THREAD

**Issue by mhauru** [EnzymeAD/Enzyme.jl#2145]
MWE:
```julia
module MWE

import Enzyme

# Two copies of the same type.
struct Normal1{T<:Real}
    σ::T
end

struct Normal2{T<:Real}
    σ::T
end

logpdf(d, x::Real) = log(d.σ) - 0.5 * (x)^2

function func(x)
    dists = [Normal1{Float64}(1.0), Normal2{Float64}(1.0)]
    return sum(n -> logpdf(dists[n], x[n]), 1:2)
end

Enzyme.gradient(Enzyme.Forward, Enzyme.Const(func), [0.5, 0.7])

end
```

Out: https://gist.github.com/mhauru/cfc7a5291b95cb8449497fe2baee38f1

On current main, Julia v1.10.6.

As in many other cases, in addition to fixing the problem, it would be great if Enzyme errors weren't gigantic dumps of intimidating LLVM stuff.

**Comment by wsmoses** [comment]
Should be resolved by https://github.com/EnzymeAD/Enzyme.jl/pull/2143

**Comment by mhauru** [comment]
Likewise confirmed fixed
