### ISSUE TITLE
illegal type analysis, Turing InverseGamma model

### ISSUE THREAD

**Issue by mhauru** [EnzymeAD/Enzyme.jl#2169]
MWE:
```julia
module MWE

import Enzyme
import ADTypes
using Turing

adbackend = ADTypes.AutoEnzyme(; mode=Enzyme.Forward)

@model function gdemo_copy()
    s ~ InverseGamma(2, 3)
end
model = gdemo_copy()

alg = HMC(0.2, 4; adtype=adbackend)
sample(model, alg, 100)

end
```

Output: https://gist.github.com/mhauru/66d6f71f82eb5fe9476dc08c8f92e263

Enzyme v0.13.17. Affects both Forward and Reverse modes.

**Comment by wsmoses** [comment]
So this is indicative of a union (which isn't presently fully supported, at least without setting Enzyme.API.strictAliasing!(false) which may permit it).

Something around here https://github.com/TuringLang/DynamicPPL.jl/blob/2252a9b6012da8e2ac56353770a0f848f6874357/src/abstract_varinfo.jl#L791 is sometimes an int and other times a double. I think this will need to be fixed on the turing side.

**Comment by mhauru** [comment]
If this is an error which may keep cropping up in normal use of Enzyme then simplifying the error message would be good.

**Comment by wsmoses** [comment]
oh yeah for sure, how about this? https://github.com/EnzymeAD/Enzyme.jl/pull/2173

**Comment by wsmoses** [comment]
Improved error messages merged, better union support is already covered in other issues.
