### ISSUE TITLE
`make_zero` of `CuArray` returns the same array instead of deep copy

### ISSUE THREAD

**Issue by utkinis** [EnzymeAD/Enzyme.jl#2186]
# Description

```julia
julia> using CUDA

julia> A = CUDA.rand(1)
1-element CuArray{Float32, 1, CUDA.DeviceMemory}:
 0.068770334

julia> make_zero(A) == A
true

julia> B = rand(1)
1-element Vector{Float64}:
 0.12168917809683022

julia> make_zero(B) == B
false
```

# Enzyme version
Enzyme v0.13.21

# Julia version
Same bug occurs both on 1.10.7 and 1.11.2

**Comment by wsmoses** [comment]
Can you reopen this on CUDA.jl? That's where the Enzyme cuda extension lives [and where the code would go]

**Comment by maleadt** [comment]
> Can you reopen this on CUDA.jl? That's where the Enzyme cuda extension lives [and where the code would go]

The Enzyme.jl extension in CUDA.jl is only hosted there for practical reasons; none of the CUDA.jl maintainers works on it. So issues regarding it should be filed on Enzyme.jl, IMO (or they risk getting ignored).

**Comment by wsmoses** [comment]
resolved by [CUDA.jl PR](https://github.com/JuliaGPU/CUDA.jl/pull/2600)
