### ISSUE TITLE
More Extensive Documentation 

### ISSUE THREAD

**Issue by maximilian-gelbrecht** [EnzymeAD/Enzyme.jl#326]
Hi there, 

I am thinking of using Enzyme for a larger project, but many things are unclear to me as the documentation is so short and really only covers the basics of the `autodiff` function. I watched your JuliaCon presentation from last year, and some of the points discussed there already helped me, but they should probably be included in some (updated) form in the documentation, like 

* GPU usage with KernelGradients
* (GPU usage with CUDA.jl?)
* How does Enzyme.jl work with the FFI 
* How does Enzyme.jl work together with ChainRules (it says in the talk that it is possible, but clunky)

**Comment by wsmoses** [comment]
@vchuravy can we copy in your presentation notebook into the docs somehow?

**Comment by wsmoses** [comment]
I think these [or the successor functionality] are now reasonably well documented
