### ISSUE TITLE
Nested broadcast not working

### ISSUE THREAD

**Issue by foldfelis** [EnzymeAD/Enzyme.jl#338]
```julia
in_dim = 2
out_dim = 3

w = rand(out_dim, in_dim)
∂l_∂w = fill!(similar(w, size(w)), 0)
b = fill!(similar(w, out_dim), 0)
∂l_∂b = fill!(similar(b, size(b)), 0)
σ = NNlib.gelu

function layer(x::AbstractVecOrMat, w, b, σ)
   return σ.(w * x .+ b)
end

x = rand(2)

autodiff(layer, Const, x, Duplicated(w, ∂l_∂w), Duplicated(b, ∂l_∂b), σ) === ()
```

The case showing above is not working. But if one cancel the activation function or the broadcast on the bias, either way will work.

**Comment by wsmoses** [comment]
Should be fixed by https://github.com/EnzymeAD/Enzyme.jl/pull/339 once that lands.

**Comment by wsmoses** [comment]
The particular code above works, but is probably not what you want since you are marking the return as constant (meaning you get zero's for the derivatives).

You likely want the following:
```
autodiff((x,y,z)->sum(layer(x,y,z)), Active, x, Duplicated(w, ∂l_∂w), Duplicated(b, ∂l_∂b), σ)
```
