### ISSUE TITLE
Support for BigFloat

### ISSUE THREAD

**Issue by LeilaGhaffari** [EnzymeAD/Enzyme.jl#348]
It seems that the Julia interface does not support BigFloat. We need this for a stability analysis of our solid mechanics examples. Would it be possible for the Enzyme team to add BigFloat to Enzyme.jl? Thanks!

**Comment by vchuravy** [comment]
Duplicate of #346

**Comment by wsmoses** [comment]
Wait you can transfer github issues between repos? TIL

**Comment by vchuravy** [comment]
Within the same org yes
