### ISSUE TITLE
Incorrect gradients with views

### ISSUE THREAD

**Issue by PVarnai** [EnzymeAD/Enzyme.jl#356]
The following code computes the minimum element at each row of a matrix, as well as the derivative with respect to the input:
```
using Enzyme
function test(x)
    rows = size(x,1)
    y = similar(x, rows)
    @inbounds for i = 1:rows
        y[i] = minimum(x[i,:])
    end
    return sum(y)
end
x = randn(3,5);
dx = zero(x)
autodiff(test, Active, Duplicated(x,dx))
display(x)
display(dx)
```
Output:
```
3×5 Matrix{Float64}:
  2.00872   -1.09518    0.466027   1.17802    1.23309
 -0.667428   0.228148  -0.552429   1.47752   -1.72691
  0.864049  -0.936399  -1.21134   -0.607346  -1.19543
3×5 Matrix{Float64}:
 0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0
 0.0  0.0  1.0  0.0  0.0
```
The 1.0's in the derivative correspond to the indices of the minimal elements in each row. However, if views are used:
```
function test_views(x)
    rows = size(x,1)
    y = similar(x, rows)
    @inbounds for i = 1:rows
        @views y[i] = minimum(x[i,:])
    end
    return sum(y)
end
dx = zero(x)
autodiff(test_views, Active, Duplicated(x,dx))
display(x)
display(dx)
```
the output is:
```
3×5 Matrix{Float64}:
  2.00872   -1.09518    0.466027   1.17802    1.23309
 -0.667428   0.228148  -0.552429   1.47752   -1.72691
  0.864049  -0.936399  -1.21134   -0.607346  -1.19543
3×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  1.0  1.0  0.0  1.0
```
which is not the same as before and is incorrect. (BTW,  differentiating through `minimum(x,dims=2)` is not yet supported.)
Also, when I tried the `@views` example with `@threads`, the compilation never finished and I could not run the code.

**Comment by wsmoses** [comment]
What version of Enzyme are you using?

**Comment by PVarnai** [comment]
It's the latest version 0.9.6.
```
(@v1.7) pkg> st Enzyme
      Status `~/.julia/environments/v1.7/Project.toml`
  [7da242da] Enzyme v0.9.6
```

**Comment by wsmoses** [comment]
Just curious, can you retry with the latest version (0.10.0), released 2 days ago. Not sure it'd fix, but would be nice to confirm.

**Comment by PVarnai** [comment]
I couldn't update Enzyme from my nominal environment, but if after `] activate temp` and `add Enzyme` (and seeing v.0.10.0 installed), going back to the repl runs that version, it is also incorrect.

**Comment by wsmoses** [comment]
Yeah I guessed it wouldn't change it -- but good to know regardless, will investigate.

**Comment by wsmoses** [comment]
Reducing further:
```julia
using Enzyme
Enzyme.API.printall!(true)
function mymin(x)
  out = 10.0
  for y in x
    out = min(out, y)
  end
  return out
end

@noinline function amapreduce_impl(A, ifirst::Integer, ilast::Integer)
    if ifirst == ilast
        @inbounds a1 = A[ifirst]
        return a1
    elseif true
        # sequential portion
        @inbounds a1 = A[ifirst]
        @inbounds a2 = A[ifirst+1]
        v = Base.min(a1, a2)
        @simd for i = ifirst + 2 : ilast
            @inbounds ai = A[i]
            v = Base.min(v, ai)
        end
        return v
    end
end

function test_views(x)
    y = 0.0
    for i in 1:2
      y += amapreduce_impl(Base.maybeview(x, i, Main.:(:)), 1, 3)
      # @views y += Base._mapreduce(Base.identity, Base.min, IndexLinear(), Base.maybeview(x, i, Main.:(:))
      # @views y += minimum(Base.maybeview(x, i, Main.:(:)))
      # @views y += mymin(x[i,:])
    end
    return y
end
x = [1.0 2.0 3.0
     5.0 4.0 6.0]
dx = zero(x)
@show x[1,:]
@show x[2,:]
@show test_views(x)
autodiff(test_views, Active, Duplicated(x,dx))
@show x
@show dx
```

**Comment by wsmoses** [comment]
```julia
using Enzyme
Enzyme.API.printall!(true)
function mymin(x)
  out = 10.0
  for y in x
    out = min(out, y)
  end
  return out
end

@noinline function amapreduce_impl(A)
    return a1
end

function test_views(x)
    y = 0.0
    for i in 1:2
      y += amapreduce_impl(Base.maybeview(x, i, Main.:(:)))
    end
    return y
end
x = [1.0 2.0 3.0
     5.0 4.0 6.0]
dx = zero(x)
@show x[1,:]
@show x[2,:]
@show test_views(x)
autodiff(test_views, Active, Duplicated(x,dx))
@show x
@show dx
```

**Comment by wsmoses** [comment]
https://github.com/EnzymeAD/Enzyme/pull/682 solves this problem.

However, as I mentioned on slack @vtjnash / @vchuravy I would much prefer an option to Julia which no longer emit invariant loads/etc on data which is not whole-program invariant (and perhaps for function-level invariant something weaker can be done/used).

**Comment by vchuravy** [comment]
In general whole program optimization can not be assumed with Julia compilation model. 

The compiler emits metadata that is correct to it's unit of compilation (function-level) and IPO/WPO is verboten. I think instead of fixing this in the Enzyme pass we should strip this as part of Enzyme.jl

Enzyme is decidedly out of the gray area and I want us to move to a similar single function at a time model since otherwise we won't be able to do effective caching.

If there is equivalent function level information we could provide upstream Julia might take those patches.

**Comment by wsmoses** [comment]
@vchuravy can we drop the old jll support and only use the latest jll, in which case we can close this issue.

**Comment by vchuravy** [comment]
https://github.com/EnzymeAD/Enzyme.jl/commit/08cc6244c2d6abc2abe5e51d5877d1e02f4e0252
