### ISSUE TITLE
MethodError when trying to autodiff through a complex matrix

### ISSUE THREAD

**Issue by golanor** [EnzymeAD/Enzyme.jl#359]
When trying to take the derivative of the `qliouville` function from the following gist: https://gist.github.com/golanor/05a4ca2ad90a257625325a43da3a789a
The following error appears:
`MethodError: no method matching similar(::Tuple{Matrix{ComplexF64}, Matrix{ComplexF64}, Vector{Float64}, Float64})`

**Comment by wsmoses** [comment]
Can you simplify your code to use Enzyme.jl directly?

**Comment by wsmoses** [comment]
Closing for lack of info, feel free to reopen
