### ISSUE TITLE
Cannot use Enzyme on clean Julia installation

### ISSUE THREAD

**Issue by RRiva** [EnzymeAD/Enzyme.jl#360]
Dear Enzyme developers,

I've tried to use Enzyme on a clean Julia installation, but it says that it cannot load libEnzyme-13.dll. Here is what I've tried.

- Open the Julia REPL and `using Enzyme`. This prints
```
  ERROR: InitError: could not load library "C:\Users\....\.julia\artifacts\435ae86b23551b6c77b1bbd7f20a23f546f45c74\bin\libEnzyme-13.dll"
The specified module could not be found.
```
- `]build Enzyme` the process runs for some seconds, and then exits without any message. Maybe there's a log file, but I don't know where.
- Exit Pkg and then `using Enzyme`. This seems to work, but when I restart the Julia REPL I get again the same error.

- I have checked. The dll is there.

**Comment by vchuravy** [comment]
What's the output of `versioninfo()`?

**Comment by vchuravy** [comment]
So there is the problem... You ended up loading libEnzyme-13 and your Julia version is using LLVM-12.

cc: @staticfloat @maleadt this smells of https://github.com/maleadt/LLVM.jl/issues/314

**Comment by staticfloat** [comment]
@RRiva Can you please try adding `Enzyme_jll` to your project (or a temporary project) and run the following:

```
using Enzyme_jll
println(Enzyme_jll.best_wrapper);
```

Can you also show me the output of:
```
println.(readdir(joinpath(Base.DEPOT_PATH[1], "compiled", "v1.7", "Enzyme_jll")));
```

I'm curious to see if `Enzyme_jll` also chooses the wrong artifact.

**Comment by RRiva** [comment]
Hi @staticfloat I've used the REPL. Here is what it says:
```
julia> using Enzyme_jll

julia> println(Enzyme_jll.best_wrapper);
C:\Users\.....\.julia\packages\Enzyme_jll\pNf5k\src\wrappers\x86_64-w64-mingw32-cxx11-llvm_version+12.jl

julia> println.(readdir(joinpath(Base.DEPOT_PATH[1], "compiled", "v1.7", "Enzyme_jll")));
HzMCj_NAOQj.ji
```

It seems that this version is the correct one, as I when I restart the REPL typing `using Enzyme_jll` works.

This time I've also tried something else. After uninstalling Julia, I've also deleted the `.julia` directory from my home folder, and then installed again. This time adding `Enzyme` and using it worked fine.

Something must have gone wrong with my previous installation. Thank you very much for your support 🙂

**Comment by maleadt** [comment]
> After uninstalling Julia, I've also deleted the `.julia` directory from my home folder, and then installed again.

That's too bad; forcing recompilation somehow resulted in the correct artifacts being picked up, which is consistent with the previous reports we've gotten on this (all related to platform augmentation, as with the LLVM issue linked above). That doesn't mean this issue is fixed, just that we can't debug it on your system anymore.

@staticfloat Can you do something with the ji files posted in https://github.com/JuliaGPU/CUDA.jl/issues/1535#issuecomment-1149153071=?

**Comment by jedbrown** [comment]
I have the following experience with a clean julia-1.10.2 (using the standard Arch Linux [`julia` package](https://archlinux.org/packages/extra/x86_64/julia/)), but it works correctly with [`julia-bin`](https://aur.archlinux.org/packages/julia-bin). I wonder if this issue is a broken Arch Linux package or the Enzyme making assumptions that are overly brittle.

I `Pkg.add("Enzyme")` and then `using Enzyme` produces
```
ERROR: LoadError: InitError: could not load library "/home/jed/.julia/artifacts/f7069537846d503d1aacae07adda0035a774b8e9/lib/libEnzyme-15.so"
/usr/bin/../lib/julia/../libLLVM-15jl.so: version `JL_LLVM_15.0' not found (required by /home/jed/.julia/artifacts/f7069537846d503d1aacae07adda0035a774b8e9/lib/libEnzyme-15.so)
Stacktrace:
 [1] __init__()
   @ Enzyme.API ~/.julia/packages/Enzyme/l4FS0/src/api.jl:550
 [2] include(fname::String)
   @ Base.MainInclude ./client.jl:489
 [3] top-level scope
   @ REPL[2]:1
during initialization of module API
in expression starting at /home/jed/lang/julia/enzyme-custom.jl:6
```
I found this thread and installed `Enzyme_jll` (which was not installed), then
```julia-repl
julia> println(Enzyme_jll.best_wrapper)
/home/jed/.julia/packages/Enzyme_jll/exFtt/src/wrappers/x86_64-linux-gnu-cxx11-llvm_version+15.jl
```
Each time I run `julia`, I have to manually `using Enzyme_jll` before `using Enzyme` will work. And yet when executing [the first example](https://enzyme.mit.edu/index.fcgi/julia/stable/generated/autodiff/), I get
```julia-repl
julia> Enzyme.autodiff(Reverse, f, Duplicated(x, bx), Duplicated(y, by));
ERROR: could not load library "/home/jed/.julia/artifacts/bb7337f7c2cf6518e0746ecfb2cc2257a383e540/lib/libLLVMExtra-15.so"
/usr/bin/../lib/julia/../libLLVM-15jl.so: version `JL_LLVM_15.0' not found (required by /home/jed/.julia/artifacts/bb7337f7c2cf6518e0746ecfb2cc2257a383e540/lib/libLLVMExtra-15.so)
Stacktrace:
  [1] LLVMAddInternalizePassWithExportList
    @ ~/.julia/packages/LLVM/OLMpi/lib/libLLVM_extra.jl:108 [inlined]
  [2] internalize!
    @ ~/.julia/packages/LLVM/OLMpi/src/transform.jl:174 [inlined]
  [3] macro expansion
    @ ~/.julia/packages/GPUCompiler/U36Ed/src/irgen.jl:112 [inlined]
  [4] macro expansion
    @ ~/.julia/packages/LLVM/OLMpi/src/base.jl:98 [inlined]
  [5] macro expansion
    @ ~/.julia/packages/GPUCompiler/U36Ed/src/irgen.jl:101 [inlined]
  [6] macro expansion
    @ ~/.julia/packages/TimerOutputs/RsWnF/src/TimerOutput.jl:253 [inlined]
  [7] irgen(job::GPUCompiler.CompilerJob)
    @ GPUCompiler ~/.julia/packages/GPUCompiler/U36Ed/src/irgen.jl:83
  [8] macro expansion
    @ ~/.julia/packages/GPUCompiler/U36Ed/src/driver.jl:202 [inlined]
  [9] macro expansion
    @ ~/.julia/packages/TimerOutputs/RsWnF/src/TimerOutput.jl:253 [inlined]
 [10] macro expansion
    @ ~/.julia/packages/GPUCompiler/U36Ed/src/driver.jl:201 [inlined]
 [11] emit_llvm(job::GPUCompiler.CompilerJob; libraries::Bool, toplevel::Bool, optimize::Bool, cleanup::Bool, only_entry::Bool, validate::Bool)
    @ GPUCompiler ~/.julia/packages/GPUCompiler/U36Ed/src/utils.jl:92
 [12] emit_llvm
    @ ~/.julia/packages/GPUCompiler/U36Ed/src/utils.jl:86 [inlined]
 [13] codegen(output::Symbol, job::GPUCompiler.CompilerJob; libraries::Bool, toplevel::Bool, optimize::Bool, cleanup::Bool, strip::Bool, validate::Bool, only_entry::Bool, parent_job::Nothing)
    @ GPUCompiler ~/.julia/packages/GPUCompiler/U36Ed/src/driver.jl:129
 [14] codegen
    @ ~/.julia/packages/GPUCompiler/U36Ed/src/driver.jl:110 [inlined]
 [15] codegen(output::Symbol, job::GPUCompiler.CompilerJob{…}; libraries::Bool, deferred_codegen::Bool, optimize::Bool, toplevel::Bool, strip::Bool, validate::Bool, only_entry::Bool, parent_job::Nothing)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/l4FS0/src/compiler.jl:4367
 [16] codegen
    @ ~/.julia/packages/Enzyme/l4FS0/src/compiler.jl:4340 [inlined]
 [17] _thunk(job::GPUCompiler.CompilerJob{Enzyme.Compiler.EnzymeTarget, Enzyme.Compiler.EnzymeCompilerParams}, postopt::Bool)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/l4FS0/src/compiler.jl:5430
 [18] _thunk
    @ ~/.julia/packages/Enzyme/l4FS0/src/compiler.jl:5430 [inlined]
 [19] cached_compilation
    @ ~/.julia/packages/Enzyme/l4FS0/src/compiler.jl:5464 [inlined]
 [20] (::Enzyme.Compiler.var"#532#533"{DataType, DataType, DataType, Enzyme.API.CDerivativeMode, Tuple{Bool, Bool, Bool}, Int64, Bool, Bool, UInt64, DataType})(ctx::LLVM.Context)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/l4FS0/src/compiler.jl:5530
 [21] JuliaContext(f::Enzyme.Compiler.var"#532#533"{DataType, DataType, DataType, Enzyme.API.CDerivativeMode, Tuple{Bool, Bool, Bool}, Int64, Bool, Bool, UInt64, DataType})
    @ GPUCompiler ~/.julia/packages/GPUCompiler/U36Ed/src/driver.jl:47
 [22] #s1883#531
    @ ~/.julia/packages/Enzyme/l4FS0/src/compiler.jl:5482 [inlined]
 [23]
    @ Enzyme.Compiler ./none:0
 [24] autodiff
    @ ~/.julia/packages/Enzyme/l4FS0/src/Enzyme.jl:209 [inlined]
 [25] autodiff
    @ ~/.julia/packages/Enzyme/l4FS0/src/Enzyme.jl:238 [inlined]
 [26] autodiff(::ReverseMode{false, FFIABI}, ::typeof(f), ::Duplicated{Vector{Float64}}, ::Duplicated{Vector{Float64}})
    @ Enzyme ~/.julia/packages/Enzyme/l4FS0/src/Enzyme.jl:224
 [27] top-level scope
    @ REPL[10]:1
Some type information was truncated. Use `show(err)` to see complete types.
```
This fails in the same way after deleting `~/.julia`.

**Comment by wsmoses** [comment]
This is a broken arch linux package. Each Julia version has a set LLVM version that it uses (which is a fork of LLVM with Julia-specific patches). I believe arch believes in one version of each dependency, which led to arch deciding to compile Julia with its system LLVM rather than the LLVM tied to Julia. Thus much of the Julia ecosystem is broken on the bundled version of Enzyme in Arch.

See https://wiki.archlinux.org/title/Julia 
```
Note: The [julia](https://archlinux.org/packages/?name=julia) package is compiled against system libraries and is therefore unsupported by the upstream. While it may be suitable for basic usage it is incompatible with external packages (e.g. MKL, LLVM, LLVMExtra, or packages that depend on these, like CUDA or Flux) which rely on Julia's bundled versions of its dependencies. For example, Sundials.jl (which is a dependency of DifferentialEquations.jl) [fails](https://github.com/SciML/Sundials.jl/issues/358) to precompile with this package, but builds without errors with the official builds. Bugs reported to Julia's maintainers against this binary will be [closed](https://github.com/JuliaLinearAlgebra/MKL.jl/issues/105#issuecomment-1025985667).
```

The usual recommendation I see is to not use the Arch system julia, for this reason.

**Comment by wsmoses** [comment]
Specifically per https://github.com/JuliaLinearAlgebra/MKL.jl/issues/105#issuecomment-1025985667

"Don't use that package. Use [aur:julia-bin](https://aur.archlinux.org/packages/julia-bin/) instead, which simply ships the official binaries:"

**Comment by jedbrown** [comment]
Thanks, I filed [an issue for `extra/julia`](https://gitlab.archlinux.org/archlinux/packaging/packages/julia/-/issues/3). I had used `aur/julia-bin` some years ago and switched back to `extra/julia` when it seemed to be working (and then forgot). It uses [`extra/llvm-julia-libs`](https://archlinux.org/packages/extra/x86_64/llvm-julia-libs/), which is supposed to match, but evidently doesn't work as intended. I switched to `juliaup`, which has resolved the issues up-thread.
