### ISSUE TITLE
Jacobian producing unexpected results

### ISSUE THREAD

**Issue by raminammour** [EnzymeAD/Enzyme.jl#377]
Hello again,

In trying to produce the pushforward[](https://discourse.julialang.org/t/pushforward-in-enzyme-jl/83921), I tried this approach to take advantage of the jacobian
```
function dbla2(d,c,dc)
    inner(e) = (c.+e.*dc).^2
    Enzyme.jacobian(Enzyme.ForwardMode(),inner,[0.])
end
dbla2(ddd,ones(3),2*ones(3))
3-element Vector{Float64}:
 6.0
 6.0
 6.0
```
Which is wrong, `2*c*dc = 4*ones(3)`. Is this a bug, or am I doing something wrong, again :)

**Comment by wsmoses** [comment]
Debugging:

```julia
using Enzyme

Enzyme.API.runtimeActivity!(true)
Enzyme.API.printall!(true)
Enzyme.API.printactivity!(true)
function dbla()
        c = ones(3)
        inner(e) = c .+ e
        Enzyme.autodiff(Enzyme.Forward, inner, Duplicated([0.], [1.]))
end

@show dbla()
```

**Comment by wsmoses** [comment]
In essence the bug comes from the fact that the outside variable comes from the closure hits a runtime activity analysis issue.

**Comment by wsmoses** [comment]
With the jll bump on main this should be fixed, even without runtime activity. Please reopen if that is not the case.
