### ISSUE TITLE
Problems for CUDA.jl kernel autodiff

### ISSUE THREAD

**Issue by classner** [EnzymeAD/Enzyme.jl#378]
Hi @wsmoses, @vchuravy!

Thanks for the great package! I'm currently exploring gradients for a function in CUDA and ran into multiple issues:

* Already commented in #375 for functions that are not available,
* I was unable to get plain CUDA kernels to compile, built just using the CUDA.jl package. An example on this end would be great to have! The only way to get things working was using KernelAbstractions.jl and using an @kernel function, for which there are probably special handlers in Enzyme.
* The resulting function is *extremely* slow. I'm observing a slow-down between 10x and 100x comparing the forward-only execution as opposed to the Enzyme autodiff-ed version of the same function. Any ideas on what could cause this?

**Comment by classner** [comment]
Thanks for the pointer @vchuravy ! The trick was to use `autodiff_deferred`. Would be great to see an example in the docs!

If the slowdown is expected, then this issue is closed.

**Comment by wsmoses** [comment]
If you're able to, posting the code with the strange performance behavior would be appreciated and we can look into it.
