### ISSUE TITLE
Segmentation fault when puting a complex number to power 0

### ISSUE THREAD

**Issue by gaspardbb** [EnzymeAD/Enzyme.jl#381]
Hi, 

I've encountered a bug with Enzyme which took me a while to localize. Basically, the following code results in a segmentation fault: 

```julia
using Enzyme

function aux(f, μ)
    result = 0.0im

    z = exp(im)
    result += z^μ   #  Bug here

    result
end

g = 1.0
μ = 0
loss(g, μ) = sum(abs.(aux(g, μ)))

@show loss(g, μ)
autodiff(Reverse, loss, Active, Active(g), μ)
```

Having non-zero power _or_ a float power _or_ a real number in `z` does not cause the segfault. 

I have `Enzyme v0.10.4` and Julia 1.7. Obviously I don't fancy optimizing such functions but I can provide context if needed! :)

**Comment by wsmoses** [comment]
Can you paste whatever you see in a log/backtrace?

I'm not able to reproduce it from your code snippet on main.

```julia
julia> using Enzyme


julia>

julia> function aux(f, μ)
           result = 0.0im

           z = exp(im)
           result += z^μ   #  Bug here

           result
       end
aux (generic function with 1 method)

julia>

julia> g = 1.0
1.0

julia> μ = 0
0

julia> loss(g, μ) = sum(abs.(aux(g, μ)))
loss (generic function with 1 method)

julia>

julia> @show loss(g, μ)
loss(g, μ) = 1.0
1.0

julia> autodiff(Reverse, loss, Active, Active(g), μ)

(0.0,)
```

**Comment by gaspardbb** [comment]
Sure, here it is 
```
signal (11): Segmentation fault: 11
in expression starting at REPL[20]:1
unknown function (ip: 0x10e7d7c6c)
Allocations: 33515273 (Pool: 33500453; Big: 14820); GC: 40
```
I'm on Mac M1 with an intel build (Rosetta). So that may be a problem.

**Comment by vchuravy** [comment]
@gaspardbb does this still reproduce for you?

**Comment by gaspardbb** [comment]
Just tried with Enzyme v0.10.11 and Julia 1.8 (M1 build) and this does not reproduce! We can close the issue.
