### ISSUE TITLE
limitations of CUDA kernels differentiation

### ISSUE THREAD

**Issue by jakubMitura14** [EnzymeAD/Enzyme.jl#383]
Hello apart from fact that Julia 1.7 is needed - are there any other constraints?

For example can one use grid synchronization or  tensor cores wmma ?

**Comment by vchuravy** [comment]
I don't think we have tried WMMA or grid synchronization! But you could give it a go and open issues with the errors you are seeing.

**Comment by wsmoses** [comment]
We may have some WMMA support (it is in tests), but I'm not sure its complete https://github.com/EnzymeAD/Enzyme/blob/5fe71401cfe29c2b9a1d0917c5946bb087687cea/enzyme/test/TypeAnalysis/tensorcore.ll

If you have code that uses and it doesn't, we can add it!

**Comment by jakubMitura14** [comment]
Thank you! I will do as you suggest!
