### ISSUE TITLE
differentiation works on cpu, fails on gpu, for exponentiation

### ISSUE THREAD

**Issue by tmbdev** [EnzymeAD/Enzyme.jl#412]
I'm trying to differentiate this kernel with Enzyme:

```
@kernel function dist_kernel!(@Const(x), @Const(y), result)
    i, j = @index(Global, NTuple)
    tmp = zero(eltype(result))
    for k = 1:size(x, 1)
        tmp += (x[k, i] - y[k, j]) ^ 4
    end
    tmp = tmp ^ (1.0 / 4)
    result[i, j] = tmp
end
```

This fails in the exponentiation with 

```
cannot handle (reverse) unknown intrinsic
llvm.nvvm.fabs.ftz.f
  %59 = call float @llvm.nvvm.fabs.ftz.f(float %51) #16, !dbg !187
```

but it only fails on GPU. It seems to me that the derivative of exponentiation is something that ought to be supported on both CPU and GPU. The culprit seems to be that exponentiation generates a call to `abs` no matter what, and that Enzyme doesn't know how to compute a derivative of `abs`. (I also have similar problems when putting a `sqrt` in the kernel.)

Complete source code, output, Project.toml, and Manifest.toml are found in this Gist:

https://gist.github.com/tmbdev/b1ed5c3964fc4ded0d530dc2869e0aaf

**Comment by wsmoses** [comment]
Can you try latest main. This was resolved recently and I'm not sure we cut a new release.

**Comment by tmbdev** [comment]
Thanks; I think that fixed it. It might be worth making a bug fix release.
