### ISSUE TITLE
BLAS fallback has short-circuiting zero path

### ISSUE THREAD

**Issue by kirimaru-jp** [EnzymeAD/Enzyme.jl#445]
Here is an example where Enzyme.jl gave the wrong gradients when the input set to zeros
```
const A::Matrix{Float64} = [1 0; 1 0; 1 0; 1 0; 1 0]
const B::Matrix{Float64} = [0 0; 0 0; 0 0; 1 0; 0 1]
f1(x) = sum( A*x[1:2] .+ B*x[3:4] );

d_dx = zeros(4); d_dx1 = zeros(4);
d_dx .= 0; Enzyme.autodiff( Reverse, x -> f1(x), Active, DuplicatedNoNeed(zeros(4), d_dx) )
d_dx1 .= 0; Enzyme.autodiff( Reverse, x -> f1(x), Active, DuplicatedNoNeed(ones(4)./10, d_dx1) )
```

```
julia> d_dx
4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

julia> d_dx1
4-element Vector{Float64}:
 5.0
 0.0
 1.0
 1.0
```

The gradients of `f1` should not depend on the values of the input, because `f1(x) = 5x₁ + x₃ + x₄`.
Hence `d_dx1` is correct.

Enzyme was updated to the newest Github version (with Julia 1.8.0)
```
(@v1.8) pkg> st Enzyme
  [7da242da] Enzyme v0.10.4 `https://github.com/EnzymeAD/Enzyme.jl#main`
```

There are some warnings

> warning: Linking two modules of different target triples: 'bcloader' is 'x86_64-w64-windows-gnu' whereas 'text' is 'x86_64-w64-mingw32'
> 
> warning: Linking two modules of different target triples: 'bcloader' is 'x86_64-w64-windows-gnu' whereas 'text' is 'x86_64-w64-mingw32'
> 
> ┌ Warning: Using fallback BLAS replacements, performance may be degraded
> └ @ Enzyme.Compiler D:\JuliaPkgs\packages\GPUCompiler\jVY4I\src\utils.jl:35
> warning: didn't implement memmove, using memcpy as fallback which can result in errors
> warning: didn't implement memmove, using memcpy as fallback which can result in errors

Update: expanding the matrix multiplication gave the correct gradients

```
function f2(x)
    Ax = zeros(5)
    for i = 1:size(A)[1]
        @views Ax[i] = sum( A[i,:] .* x[1:2] )
    end
    Bx = zeros(5)
    for i = 1:size(B)[1]
        @views Bx[i] = sum( B[i,:] .* x[3:4] )
    end
    return sum(Ax .+ Bx)
end

d2_dx = zeros(4); d2_dx1 = zeros(4);
d2_dx .= 0; Enzyme.autodiff( Reverse, x -> f2(x), Active, DuplicatedNoNeed(zeros(4), d2_dx) )
d2_dx1 .= 0; Enzyme.autodiff( Reverse, x -> f2(x), Active, DuplicatedNoNeed(ones(4)./10, d2_dx1) )
```

```
julia> d2_dx
4-element Vector{Float64}:
 5.0
 0.0
 1.0
 1.0

julia> d2_dx1
4-element Vector{Float64}:
 5.0
 0.0
 1.0
 1.0
```

**Comment by wsmoses** [comment]
Looks like the fallback BLAS library we use, actually does this as its implementation. In other words, special case having a check if the input is 0 and if so not doing anything (which when we differentiate, we correctly dont go down that path).

See: https://github.com/ampl/gsl/blob/6e40fb13a501393f3a9deb7c4fcbee85241a0339/cblas/source_gemv_r.h#L80

Fixing that requires a patch to the jll to modify this.

**Comment by wsmoses** [comment]
Keeping this open until we bump jll (but landed fix in enzyme proper)

**Comment by wsmoses** [comment]
This now landed on main.
