### ISSUE TITLE
Custom tapes using foreing types support in Julia

### ISSUE THREAD

**Issue by vchuravy** [EnzymeAD/Enzyme.jl#523]
Currently Enzyme.jl uses `NamedTuple` to describe it's custom layouts...
This leads to all sort of issues, most recently #407 

An alternative design we considered, but discarded at the time is to use the `jl_new_foreing_type` feature to provide our own mark/sweep function and support arbitrary datalayouts. At the time we discarded it since we would still need a pointer somewhere for the layout descriptor.

`jl_new_foreign_type` uses:

```
  jl_datatype_layout_t *layout = (jl_datatype_layout_t *)
      jl_gc_perm_alloc(sizeof(jl_datatype_layout_t) + sizeof(jl_fielddescdyn_t),
        0, 4, 0);
```

To create extra space for the `jl_fielddescdyn_t`, we could use the same technique to add a custom `jl_enzyme_layout_t`.

@fingolfin would a pointer to stash a custom datalayout be helpful for your use-case?

**Comment by fingolfin** [comment]
@vchuravy only just now noticed this issue resp. this AT-mention of me, sorry. 

I don't quite understand what you write here resp. what the concrete proposal is regarding `jl_new_foreign_type`... but for GAP, we don't use those datalayouts at all. So I guess that means my answer is "no" for the moment.

**Comment by vchuravy** [comment]
I think we found an independent solution using NamedTuples to synthesize a Datalayout on-demans
