### ISSUE TITLE
Unknown intrinsic when diffing through cbrt(x::Float32) but not with Float64

### ISSUE THREAD

**Issue by sefffal** [EnzymeAD/Enzyme.jl#541]
Enzyme is able to differentiate through `cbrt` with Float64, but not Float32:

```julia
Enzyme.autodiff(cbrt, Active(1.0f0))
```

Gives:
`cannot handle unknown binary operator:   %6 = and i32 %5, 2147483647, !dbg !25`

N.B. this is not currently something I would like to do, but noting it here in case it's useful.
If these unknown intrinsic issues aren't helpful at this stage, let me know and I'll avoid submitting them.

**Comment by tgymnich** [comment]
Both derivatives don't work.
For `Float64` Enzyme is only differentiating an approximation of `cbrt` and for `Float32` it fails to differentiate, since it finds some bit manipulation instructions to be inactive (which is not the case for `Float64`).

This should be easy to fix after #177 lands.

**Comment by wsmoses** [comment]
This was resolved in https://github.com/EnzymeAD/Enzyme/pull/919 but we need to make the jll

**Comment by wsmoses** [comment]
This should now be resolved on main. Retry and confirm?
