### ISSUE TITLE
Bug with code in unused branches.

### ISSUE THREAD

**Issue by jlk9** [EnzymeAD/Enzyme.jl#554]
![Screen Shot 2022-12-12 at 5 03 16 PM](https://user-images.githubusercontent.com/16888623/207175249-66583fdf-a528-49e2-b2b4-c8c490de21ba.png)
![Screen Shot 2022-12-12 at 5 03 32 PM](https://user-images.githubusercontent.com/16888623/207175258-0f19882f-6c66-4030-8ec5-2481bbf4f442.png)
[enzyme_bug.zip](https://github.com/EnzymeAD/Enzyme.jl/files/10212621/enzyme_bug.zip)

Encountering a bug with conditional statements. This code should ignore the if statement since Foo.a = 1.0 > 0.0. However, Enzyme appears to still try to compute X and c inside the conditional, which causes an error since (-1.0)^0.25 produces a complex number. This error doesn't occur if the additional computations for c and Foo.b[1] are removed.

@wsmoses

**Comment by jlk9** [comment]
```julia
using Enzyme

mutable struct Foo

    iters::Int64
    a::Float64
    b::Vector{Float64}

end

function f(Foo)
    for i = 1:Foo.iters

        c = -1.0

        if Foo.a < 0.0
            X = (-Foo.a)^0.25
            c = 2*log(X)
        end

        # set b equal to desired result
        Foo.b[1] = 1.0 / c

        return nothing
    end
end

foo  = Foo(1, 1.0, zeros(Float64, 1))
dfoo = Foo(0, 0.0, zeros(Float64, 1))

Enzyme.API.printall!(true)

Enzyme.autodiff(f, Duplicated(foo, dfoo))
```

**Comment by wsmoses** [comment]
This should now be fixed on main without the workaround. Retry and confirm?
