### ISSUE TITLE
Segfault when allocating in a loop

### ISSUE THREAD

**Issue by chrhck** [EnzymeAD/Enzyme.jl#559]
This pieces of code causes a segfault on julia 1.8.3 and Enzyme v0.10.12
Note: The code doesn't do anything useful, but I believe this causes the issue I see in a more complex piece of code, where I assign the allocated arrays in the inner loop to an array I define outside the loop.
Also note that pulling the allocation out of the loop (or using `for k in 1:1) causes no isses.
```
using Enzyme

function test(x)
    n = 1
    for k in 1:2
        y = falses(n)        
    end
    return x
end
a = Enzyme.autodiff(Enzyme.Reverse, test, Active, Active(1E4))
```
```
signal (11): Segmentation fault
in expression starting at /home/chrhck/repos/NeutrinoTelescopes/scripts/repr_enzyme_crash.jl:10
_ZNK4llvm10BasicBlock10getContextEv at /home/chrhck/.julia/juliaup/julia-1.8.3+0.x64.linux.gnu/bin/../lib/julia/libLLVM-13jl.so (unknown line)```

**Comment by wsmoses** [comment]
This will be fixed by https://github.com/EnzymeAD/Enzyme/pull/957 but will require a jll bump before it is available to the Julia bindings.

**Comment by chrhck** [comment]
If I've understood the issue correctly, then the segfault in this case has to do with the fact that the loop is essentially a noop for calculating the gradient? In this case it's probably not the cause of the issue I'm seeing with the more complex code. I'll dig further...

**Comment by wsmoses** [comment]
Yeah this is distinct from what you posted on slack -- but nevertheless a good bug to fix!

Which now should be fixed on main if you can retry.
