### ISSUE TITLE
Linking two modules of different target triples: 'bcloader' is 'arm64-apple-macosx11.0.0' whereas 'text' is 'arm64-apple-darwin21.5.0'

### ISSUE THREAD

**Issue by Roger-luo** [EnzymeAD/Enzyme.jl#607]
I'm trying the following code on `main` (1e1de321d6610dfd73e26805fbb8fe6ecd48497c)

```julia
julia> autodiff(Reverse, (x,y)->sum(x*y), Duplicated(A, dA), Duplicated(B, dB))
warning: Linking two modules of different target triples: 'bcloader' is 'arm64-apple-macosx11.0.0' whereas 'text' is 'arm64-apple-darwin21.5.0'

warning: Linking two modules of different target triples: 'bcloader' is 'arm64-apple-macosx11.0.0' whereas 'text' is 'arm64-apple-darwin21.5.0'

warning: Linking two modules of different target triples: 'bcloader' is 'arm64-apple-macosx11.0.0' whereas 'text' is 'arm64-apple-darwin21.5.0'

┌ Warning: Using fallback BLAS replacements, performance may be degraded
└ @ Enzyme.Compiler ~/.julia/packages/GPUCompiler/qdoh1/src/utils.jl:50
((nothing, nothing),)
```

I'm not sure why I got these warnings, any idea how to get rid of them? and I'm wondering why it will use fallback BLAS here?

```julia
julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.5.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
```

**Comment by wsmoses** [comment]
Presuming A and B are matrices, A*B will call BLAS. Currently we only have a fallback BLAS implementation available, hence the warning. Having a non fallback implementation is on our to do list, but it should nevertheless get the correct answer -- but perhaps not quite as fast.

**Comment by luraess** [comment]
Being the same warnings when running the latest Enzyme test suite on ARM-based Apple M2 MacBook Air CPU (Enzyme v0.10.18, Julia v1.8.5):
```
warning: Linking two modules of different target triples: 'bcloader' is 'arm64-apple-macosx11.0.0' whereas 'text' is 'arm64-apple-darwin21.5.0'

warning: Linking two modules of different target triples: 'bcloader' is 'arm64-apple-macosx11.0.0' whereas 'text' is 'arm64-apple-darwin21.5.0'

┌ Warning: Using fallback BLAS replacements, performance may be degraded
└ @ Enzyme.Compiler ~/.julia/packages/GPUCompiler/qdoh1/src/utils.jl:50
Test Summary: | Pass  Total  Time
Dot product   |    3      3  3.0s
warning: Linking two modules of different target triples: 'bcloader' is 'arm64-apple-macosx11.0.0' whereas 'text' is 'arm64-apple-darwin21.5.0'

warning: Linking two modules of different target triples: 'bcloader' is 'arm64-apple-macosx11.0.0' whereas 'text' is 'arm64-apple-darwin21.5.0'

┌ Warning: Using fallback BLAS replacements, performance may be degraded
└ @ Enzyme.Compiler ~/.julia/packages/GPUCompiler/qdoh1/src/utils.jl:50
```

**Comment by Roger-luo** [comment]
> Presuming A and B are matrices, A*B will call BLAS. Currently, we only have a fallback BLAS implementation available, hence the warning. 

I'm not sure if I understand this correctly, but would define a rule for this would resolve it?

**Comment by wsmoses** [comment]
Yeah that would resolve it. @ZuseZ4 was earlier working on the internal non fallback method. Both of these would be good to explore (and have benefits for different use cases which we could use a heuristic to swap between).

**Comment by wsmoses** [comment]
I've also made a change to Enzyme proper so then you will only get the Julia level and not LLVM level warning the next time that we bump the jll

**Comment by wsmoses** [comment]
In any case @Roger-luo stress testing custom rules would definitely be helpful for us, if you want to write Julia-level ones for blas/etc in EnzymeRules

**Comment by wsmoses** [comment]
Closing this as the warning of module scope should be gone from main. @Roger-luo still would be amazing if you have time to do BLAS rules.
