### ISSUE TITLE
Gradient computation "corrupted" on ARM-based M2 CPU

### ISSUE THREAD

**Issue by luraess** [EnzymeAD/Enzyme.jl#611]
I was in touch with @vchuravy about an issue we have when computing the gradients using Enzyme on ARM-based M2 Apple CPU within this code https://github.com/PTsolvers/PoroElast.jl/blob/main/scripts/campi_flegrei_adjoint_2d.jl.

We see that the functions reported in https://github.com/PTsolvers/PoroElast.jl/issues/1 return inaccurate gradient values in some parts of the domain after a few calls. This results in non-converging iterations.

All works fine when running the same codes on Windows and Linux x86-based Intel and AMD CPUs, as well as Nvidia GPUs. This is seen on Julia v1.8.5 using latest Enzyme v0.18.10.

**Comment by wsmoses** [comment]
Can you add an Enzyme.API.printall!(true) and attach the log?

**Comment by luraess** [comment]
Here you go @wsmoses [out_log.txt](https://github.com/EnzymeAD/Enzyme.jl/files/10668776/out_log.txt)

**Comment by wsmoses** [comment]
There seem to be a ton of bound checks, to simplify mind adding @inbounds everywhere?  Also is this using parallelism in any way?

**Comment by luraess** [comment]
Running **without** bound checks `Julia --project --check-bounds=no` not in REPL results in expected execution of the adjoint solve involving Enzyme generated gradient (`iter/ny # 36.0`). See [out_1.txt](https://github.com/EnzymeAD/Enzyme.jl/files/10684522/out_1.txt) and [out_2.txt](https://github.com/EnzymeAD/Enzyme.jl/files/10684524/out_2.txt).

However, **with** bound checking, running not in the REPL results in non stable behaviour leading to incorrect execution in [out_3.txt](https://github.com/EnzymeAD/Enzyme.jl/files/10684545/out_3.txt) but in correct results in [out_4.txt](https://github.com/EnzymeAD/Enzyme.jl/files/10684551/out_4.txt) and [out_5.txt](https://github.com/EnzymeAD/Enzyme.jl/files/10684552/out_5.txt).

Interestingly, running from the **REPL without** bound checking results in non stable execution, see [repl_checkbounds_no.txt](https://github.com/EnzymeAD/Enzyme.jl/files/10684561/repl_checkbounds_no.txt).

**Comment by luraess** [comment]
Actually, I also see unexpected results **without** bound checks **not** within the REPL. Attached is a "failing" run 
[failing_out.txt](https://github.com/EnzymeAD/Enzyme.jl/files/10687856/out_new_1.txt) and a successful one 
[success_out.txt](https://github.com/EnzymeAD/Enzyme.jl/files/10687863/out_new_2.txt).

**Comment by luraess** [comment]
Actually, answering
> Also is this using parallelism in any way?

Seems to be a good hint: I had `nthreads=4`. Forcing a single thread seems to definitively resolve the issue on ARM CPU. See output [out_1thread.txt](https://github.com/EnzymeAD/Enzyme.jl/files/10688222/out_1thread.txt)

**Comment by luraess** [comment]
Any new insights on this? 🙏

**Comment by wsmoses** [comment]
We really need a version just calling Enzyme, that is as small as possible in order to investigate. Any chance you can minimize further?

**Comment by wsmoses** [comment]
@luraess does this still err?

**Comment by luraess** [comment]
Nothing I can reproduce for now. I will close it and may re-open if needed.
