### ISSUE TITLE
Add support for ENABLE_JITPROFILING for both perf and Vtunes

### ISSUE THREAD

**Issue by vchuravy** [EnzymeAD/Enzyme.jl#633]
https://github.com/EnzymeAD/Enzyme.jl/blob/ed26d9c7528a327058cbd6a8ae16d5b36a7968aa/src/compiler/orcv1.jl#L32

**Comment by wsmoses** [comment]
@vchuravy this exists in orcv2, can this be added to orcv1? https://github.com/EnzymeAD/Enzyme.jl/blob/0e481138e3907d85b69dd3283f0da794a4b138a2/src/compiler/orcv2.jl#L71

**Comment by wsmoses** [comment]
Going to close as not planned
