### ISSUE TITLE
Wrong gradients when modifying a vector in a struct

### ISSUE THREAD

**Issue by ptiede** [EnzymeAD/Enzyme.jl#639]
I just noticed I got the wrong gradients for some of my functions. When I modify a vector stored in a struct, the gradients aren't getting propagated. Here is a MWE 

```julia
struct Test{T}
    buffer::T
end

function (t::Test)(x)
    t.buffer .= x.^2
    return sum(t.buffer)
end


ndim = 10
x0 = randn(ndim)
test = Test(zero(x0))

test(x0)

dx0 = zero(x0)
autodiff(Reverse, test, Active, Duplicated(x0, dx0))
dx0 # returns [0.0, 0.0, ...]

autodiff(Forward, test, Duplicated(x0, dx0))
dx0 # returns [0.0, 0.0, ...]
```

If I update the argument `x` in place, then everything seems to work
```julia
function test2!(x)
    x .= x.^2
    return sum(x)
end

test2!(x0)
autodiff(Reverse, test2!, Active, Duplicated(copy(x0), fill!(dx0, 0.0)))
dx0 ≈ 2 .* x0
```

## Computing Environment
My Project is 
```julia
  [7da242da] Enzyme v0.11.0-dev `https://github.com/EnzymeAD/Enzyme.jl.git#main`
  [f151be2c] EnzymeCore v0.2.1 `https://github.com/EnzymeAD/Enzyme.jl.git:lib/EnzymeCore#main`
```
and my computing environment is
```julia
Julia Version 1.9.0-beta4
Commit b75ddb787ff (2023-02-07 21:53 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 32 × AMD Ryzen 9 7950X 16-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver3)
  Threads: 1 on 32 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 1
```

**Comment by wsmoses** [comment]
Forward mode only propagates gradients from inputs to outputs, so dx0 not being modified is expected (but the return value of autodiff should have the derivative).

Also nevertheless, this is seemingly expected since the closure is marked as const. You need to pass Duplicated(test, dtest) as the closure function.

**Comment by ptiede** [comment]
Ok good to know! I think I am still seeing an issue using forward mode. When I 
```julia
autodiff(Forward, test, Duplicated(x0, dx0))
```
just returns (0.0,) and when I change it to
```julia
dtest = Test(zero(x0))
autodiff(Forward, Duplicated(test, dtest), Duplicated(x0, dx0))
```
I see the same thing.

The reverse mode was fixed by passing a duplicated struct. I noticed that this is in the docs, and I just missed it.

**Comment by wsmoses** [comment]
Yeah forward mode propagates the input derivatives to the outputs.

Since you say `dx0 = zero(x0)`. It'll propagate 0 for all inputs.

Make dx0[1] = 1.0 and you'll get the derivative wrt the first element. Set dx0[2] = 1.0 and you'll get the derivative wrt the second. Set both to 1.0 and you'll get 1.0 * the derivative wrt the first + 1.0 * the derivative wrt the second, etc.

**Comment by ptiede** [comment]
Oh sorry for being slow there. Ok so for Enzyme forward mode you need to propagate the gradient in each direction separately. So use something like BatchDuplicated.

**Comment by wsmoses** [comment]
Yeah so forward mode propagates from inputs to outputs (and thus gives you the derivative of all outputs wrt a given input [or technically the linear sum of derivatives wrt inputs]), and reverse mode from outputs to inputs.

**Comment by ptiede** [comment]
Ya, that makes sense I was under the wrong assumption that it worked like ForwardDiff and did the propagation for each direction and then summed everything together. 

Now for some explanation. The reason I went down this rabbit hole is that when I am trying to differentiate through some of my code the gradient is wrong and its value is changing from evaluation to evaluation even when I hold the arguments fixed and zero out dx. This seems entirely different so I'll need to find a different MWE.
