### ISSUE TITLE
Enzyme is modifying variables in a struct that is not part of active data

### ISSUE THREAD

**Issue by ptiede** [EnzymeAD/Enzyme.jl#640]
I noticed that stored data in a struct seems to be modified when running Enzyme. Here is a MWE

```julia
struct Test2{T}
    obs::T
end

function (t::Test2)(x)
    y = (x .- t.obs).^2
    return sum(y)
end

ndim = 10
obs = ones(ndim)
test = Test2(obs)


x0 = zeros(ndim)
test(x0)

dx0 = zero(x0)
autodiff(ReverseWithPrimal, test, Duplicated(x0, fill!(dx0, 0.0)))
println(obs) # returns [3.0, 3.0, ...]
```

So it appears that that `autodiff` is accumulating gradients into `obs` even though the variable should be constant. If I instead do
```julia
autodiff(Reverse, Duplicated(test, Test2(zeros(ndim)), Duplicated(x0, fill!(dx0, 0.0)))
```
then `test.obs` isn't modified and interestingly nothing is accumulated into the shadow.

I am using the main branch of Enzyme and Julia 1.9.0-beta4 but see similar behavior in 1.8.5.

**Comment by vchuravy** [comment]
@tgymnich this reminds me of #635.

**Comment by wsmoses** [comment]
Activity analysis here is being too aggressive. In the interim if you add Enzyme.API.runtimeActivity!(true) beforehand, this should resolve.

**Comment by wsmoses** [comment]
Reduced: 
```julia
using Enzyme

Enzyme.API.printall!(true)
Enzyme.API.printactivity!(true)

struct Test2{T}
    obs::T
end

function test(t, x)
	o = t.obs
    y = (x .- o)
	yv = @inbounds y[1]
    return yv*yv
end

obs = [1.0]
t = Test2(obs)

x0 = [0.0]
dx0 = [0.0]

# Enzyme.API.runtimeActivity!(true)

autodiff(Reverse, test, Const(t), Duplicated(x0, dx0))

println(obs) # returns [3.0, 3.0, ...]
```

**Comment by wsmoses** [comment]
Fixed by https://github.com/EnzymeAD/Enzyme/pull/1012, but requires a jll bump
