### ISSUE TITLE
Parameter unpacking yields `ERROR`s

### ISSUE THREAD

**Issue by simsurace** [EnzymeAD/Enzyme.jl#677]
I have started trying out Enzyme.jl for some applications. A lot of things already seem to be working nicely!

This is a pattern that is used quite often to convert from named parameters to vectors and applying transformations for optimization (e.g. in [ParameterHandling.jl](https://github.com/invenia/ParameterHandling.jl)). Here is a M(n)WE:

```julia
using Enzyme

f(par::NamedTuple) = par.a * par.b + par.c
par = (a = 1., b = 2., c = 3.)
autodiff(Reverse, f, Active(par)) # works beautifully and efficiently

unpack_vector(vec::Vector) = (a = vec[1], b = vec[2], c = vec[3])
vec = [1., 2., 3.]
autodiff(Reverse, f ∘ unpack_vector, Active(vec)) # ERROR: Conversion of boxed type Vector{Float64} is not allowed
```

In a slightly different example, sometimes the error reads `ERROR: Duplicated Returns not yet handled`.

**Comment by wsmoses** [comment]
You need to use duplicated for arrays

**Comment by theogf** [comment]
Is there a way to catch this error and to return a more informative message?

**Comment by wsmoses** [comment]
Agreed (https://github.com/EnzymeAD/Enzyme.jl/issues/318), PR's welcome :)
