### ISSUE TITLE
gc seg fault

### ISSUE THREAD

**Issue by motabbara** [EnzymeAD/Enzyme.jl#727]
Private repo -- works fine in 1.9rc2 but gc seg fault in nightly.

[out.txt](https://github.com/EnzymeAD/Enzyme.jl/files/11216777/out.txt)

**Comment by wsmoses** [comment]
@motabbara retry? I think I fixed the nightly GC offset

**Comment by wsmoses** [comment]
Reopen if persists.

**Comment by motabbara** [comment]
Thanks @wsmoses. This segfault is gone. I have a new one under different conditions and will report separately once I can reliably repro.
