### ISSUE TITLE
Segfault when rerunning gradient computation multiple times

### ISSUE THREAD

**Issue by zornsllama** [EnzymeAD/Enzyme.jl#737]
Hi,

I am trying to use Enzyme.jl to compute the gradient of a scalar objective function with large input. When I run the gradient computation once, it seems like everything has worked correctly. When I then run the computation once more, I immediately get a segfault. Please see the attached minimal working example and the console output.

[mwe_enzyme.jl.txt](https://github.com/EnzymeAD/Enzyme.jl/files/11257977/mwe_enzyme.jl.txt)
[mwe_enzyme_log.txt](https://github.com/EnzymeAD/Enzyme.jl/files/11257972/mwe_enzyme_log.txt)

Curious why this is happening (and also if I'm doing something wrong/using the package incorrectly). Any help is much appreciated!

**Comment by wsmoses** [comment]
Seemingly fixed on main by https://github.com/EnzymeAD/Enzyme.jl/pull/772 please reopen if it persists.
