### ISSUE TITLE
Error when using closure over type

### ISSUE THREAD

**Issue by simsurace** [EnzymeAD/Enzyme.jl#741]
This errors:
```julia
using Enzyme
function foo(x::Tuple{T}) where {T<:AbstractVector}
    constructor = typeof(only(x))
    function bar(v)
        return (constructor(v),)
    end
    return only(x), bar
end

f(t) = sum(only(t))
t = (rand(10),)
x, u = foo(t)
dx = zero(x)
autodiff(Reverse, f ∘ u, Duplicated(x, dx)) # ERROR: Duplicated Returns not yet handled
```
while this works:
```julia
using Enzyme
function foo(x::Tuple{T}) where {T<:AbstractVector}
    function bar(v)
        return (T(v),)
    end
    return only(x), bar
end

f(t) = sum(only(t))
t = (rand(10),)
x, u = foo(t)
dx = zero(x)
autodiff(Reverse, f ∘ u, Duplicated(x, dx))
```

**Comment by wsmoses** [comment]
This indicates that your code is type unstable in its return. Any any return is presently unsupported since its non-obvious what the corresponding += 1 would be.

forcing your function to return a say float64 will resolve.

**Comment by simsurace** [comment]
Oh, I actually did not check type stability. This was reduced from a larger code that I thought to be type stable. This looks like it should be type stable, but the closure might be problematic.

**Comment by simsurace** [comment]
Indeed due to type instability caused by the closure.
