### ISSUE TITLE
Julia Nightly custom interpreter

### ISSUE THREAD

**Issue by wsmoses** [EnzymeAD/Enzyme.jl#749]
@aviatesk there's some issue right now where on Julia Nightly, the interpreter seems not to be successfully applying (erring in the custom rules). The other 1.7, 1.8, 1.9 versions are fine. Did the api for inlining or something change?

**Comment by aviatesk** [comment]
The main change I'm aware of around inlining is https://github.com/JuliaLang/julia/pull/49404 but I confirmed Enzyme.jl test suite fails on https://github.com/JuliaLang/julia/commit/b27c87eb1d04f0bd001f32ffd134437007170984 (the previous commit) the same as on the latest master.
