### ISSUE TITLE
Incomplete sentence in docstring of `autodiff(::ForwardMode, ...)`

### ISSUE THREAD

**Issue by giordano** [EnzymeAD/Enzyme.jl#752]
https://github.com/EnzymeAD/Enzyme.jl/blob/a23e75f6d1cd35f90ec9a534515fde39d20b01c7/src/Enzyme.jl#L239-L241

**Comment by wsmoses** [comment]
Duplicate of https://github.com/EnzymeAD/Enzyme.jl/issues/698
