### ISSUE TITLE
Performance regression

### ISSUE THREAD

**Issue by michel2323** [EnzymeAD/Enzyme.jl#796]
I observed a regression issue going from Enzyme.jl `v0.11.0` to `v0.11.1`.

`v0.11.1`:
```
401.197621 seconds (69.04 M allocations: 4.089 GiB, 99.80% compilation time)
```
`v0.11.0`:
```
81.696286 seconds (46.88 M allocations: 2.844 GiB, 99.41% compilation time)
```
The pprof files are attached.

The code is the one by @swilliamson7 https://github.com/DJ4Earth/eddy-stresses/blob/main/src/main_energy_1.jl .
[profile_11.0.pb.gz](https://github.com/EnzymeAD/Enzyme.jl/files/11349501/profile_11.0.pb.gz)
[profile_11.1.pb.gz](https://github.com/EnzymeAD/Enzyme.jl/files/11349503/profile_11.1.pb.gz)

**Comment by swilliamson7** [comment]
That repo isn't set to public, but I just put the newest version of the code here: https://github.com/DJ4Earth/DJ-barotropic-gyre. The scripts Michel is referring to are in explicit_solver/src, and the file main_energy_1_chkp.jl runs the whole model

**Comment by vchuravy** [comment]
- 11.0: https://pprof.me/b214a6e/
- 11.1: https://pprof.me/b2fbacf/ (doesn't load filed an issue)

**Comment by wsmoses** [comment]
Retry on main?

**Comment by michel2323** [comment]
Some preliminary report after fiddling with it for a while. I somehow get a new error with `v0.11.1` and `main`, which drops after 8 minutes or something, when `v0.11.0` goes through as usual. Attached is the error log. I thought it's something on in our code that changed, but it may be related to the Julia version. I have to investigate more...
[bug_11.1.log](https://github.com/EnzymeAD/Enzyme.jl/files/11426109/bug_11.1.log)

**Comment by wsmoses** [comment]
@michel2323 can you rerun with this branch and post the log? https://github.com/EnzymeAD/Enzyme.jl/pull/822 It just adds some extra information so we can figure out what's going awry.

**Comment by michel2323** [comment]
@wsmoses Here are the logs. There are two. One with GC enabled and one with GC disabled because they give a different printout.
[logs.zip](https://github.com/EnzymeAD/Enzyme.jl/files/11434558/logs.zip)

**Comment by wsmoses** [comment]
@michel2323 try again on main, I think it should be fixed.
