### ISSUE TITLE
Catch local version missmatch

### ISSUE THREAD

**Issue by ZuseZ4** [EnzymeAD/Enzyme.jl#851]
Building Enzyme locally and changing the julia version will result in segfaults.
We should catch that.

```
_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE at /u/drehwald/.julia/artifacts/c90711842814121dacf839a59bca4c40f573cbff/lib/libLLVM-14jl.so (unknown line)  │~                                                
_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE at /h/344/drehwald/.julia/juliaup/julia-1.7.3+0.x64.linux.gnu/bin/../lib/julia/libLLVM-12jl.so (unknown line)
```

**Comment by wsmoses** [comment]
Described the importance of the correct version in updated devdocs: https://github.com/EnzymeAD/Enzyme.jl/pull/1436

I'm not away of a good way to support this otherwise, so closing as unplanned.

Feel free to reopen.
