### ISSUE TITLE
sincos errors for ComplexF64 forward-mode

### ISSUE THREAD

**Issue by sethaxen** [EnzymeAD/Enzyme.jl#855]
When the argument type is `ComplexF64`, forward-mode autodiff raises an error:

```julia
using Enzyme

x, ∂x = randn(ComplexF64, 2)
autodiff(Forward, sincos, Duplicated, Duplicated(x, ∂x))
```
[dump.txt](https://github.com/EnzymeAD/Enzyme.jl/files/11502578/dump.txt)

**Comment by wsmoses** [comment]
Yeah simply `autodiff(Forward, cos, Duplicated, Duplicated(x, ∂x))` fails.

Interestingly sin(complex) doesn't have the flipsign call inside that cos(complex) does.
