### ISSUE TITLE
Enzyme cannot deduce type

### ISSUE THREAD

**Issue by sethaxen** [EnzymeAD/Enzyme.jl#874]
The following raises an error "Enzyme cannot deduce type":

```julia
using Enzyme

struct Foo{X,A}
    x::X
    a::A
end

f_struct(x::Foo) = Foo(x.a .* x.x, x.a)

T = Float32
x = Foo(randn(T, 2), randn(T))
∂x = Foo(randn(T, 2), randn(T))

autodiff(Forward, f_struct, Duplicated, Duplicated(x, ∂x))  # fine
autodiff(Forward, x -> f_struct(x), Duplicated, Duplicated(x, ∂x))  # errors, see attached
```
[dump.txt](https://github.com/EnzymeAD/Enzyme.jl/files/11584309/dump.txt)

The error goes away if we remove the broadcast in `x.a .* x.x`, just return `x.a .* x.x`, or use `T=Float64`.

**Comment by wsmoses** [comment]
Duplicate cause as from https://github.com/EnzymeAD/Enzyme.jl/issues/857, closing
