### ISSUE TITLE
CUDA sin is broken

### ISSUE THREAD

**Issue by wsmoses** [EnzymeAD/Enzyme.jl#924]
There was some change such (? to CUDA.jl) that nv_sin/etc is not always ebing linked in now, which means we cannot find it to generate the derivative of nv_cos.

**Comment by wsmoses** [comment]
@vchuravy if you have any insights here

**Comment by wsmoses** [comment]
So this was broken by https://github.com/EnzymeAD/Enzyme.jl/pull/915/files aka GPUCompiler 0.20

cc @maleadt if you might have any insights here.

Essentially what used to happen is that for cuda code using device functions Enzyme/GPUCompiler would link in all of libdevice (aka sin, cos, etc). This is necessary since the derivative of nv_sin is nv_cos.

Since ?GPUCompiler 0.20, it appears that by the time Enzyme gets it, the (from the source) unused nv_cos is dropped, leaving Enzyme.jl no implementation to use on CUDA, leading to issues.

**Comment by wsmoses** [comment]
Yes, this PR: https://github.com/JuliaGPU/GPUCompiler.jl/pull/458 specifically broke Enzyme CUDA compilation here, for the reasons above.

@maleadt can we go back to having linking before codegen (otherwise we are unable to do the relevant force preservation and llvm.sin -> __nv_sin) ?

**Comment by maleadt** [comment]
> @maleadt can we go back to having linking before codegen (otherwise we are unable to do the relevant force preservation and llvm.sin -> __nv_sin) ?

Not easily, as that was a correctness fix for deferred-mode compilation. Changing it would re-introduce a bug.

You should be able to sufficiently customize the compilation already though. Where were you currently detecting `__nv_sin`?
