### ISSUE TITLE
Compilation error for custom reverse rule

### ISSUE THREAD

**Issue by wisp3rwind** [EnzymeAD/Enzyme.jl#952]
In the code sample below, a custom reverse rule is defined for a `Matrix -> Float64` function (for the sake of a minimal example, this just extracts a value from the `Matrix`).

Depending on how exactly this rule is used, it works or results in an unspecific compilation error (see the code comments). Three cases are shown in the code: In particular, the last case differs from the first only by a slight re-ordering of the arithmetic in `g2` compared to `g1`.

I'm new to Enzyme, so maybe I'm simply doing something wrong here and you could provide a hint at what's going on? If not, does this hint at a bug?

This is on Julia 1.9.2 with `Enzyme#main`.

Thanks a lot!

# MWE

```jl
using Logging
using Enzyme
using Enzyme: EnzymeRules
import .EnzymeRules: forward, reverse, augmented_primal, ConfigWidth, needs_primal, AugmentedReturn


debuglogger = ConsoleLogger(stderr, Logging.Debug)
global_logger(debuglogger)
Enzyme.API.printall!(true)

function f(C)
    C[1, 1]
end


function forward(func::Const{typeof(f)}, RT::Type{Duplicated}, C::Duplicated)
    Duplicated(C.val[1, 1], C.dval[1, 1])
end


function augmented_primal(config::ConfigWidth{1}, ::Const{typeof(f)}, RT::Type{<:Active}, C::Duplicated)
    primal = needs_primal(config) ? C.val[1, 1] : nothing
    AugmentedReturn(primal, nothing, nothing)
end

function reverse(config::ConfigWidth{1}, ::Const{typeof(f)}, dret, tape, C::Duplicated)
    C.dval[1, 1] += dret.val
    (nothing, )
end


C = rand(Float64, 10, 10)

# Works
dC = zero(C)
g1(C) = C[2, 2] + f(C)
res = autodiff(Reverse, g1, Active, Duplicated(C, dC))

# Works (difference to before: use ReverseWithPrimal, change evaluation order in g2 compared to g1)
dC = zero(C)
g2(C) = f(C) + C[2, 2]
res = autodiff(ReverseWithPrimal, g2, Active, Duplicated(C, dC))

# Compilation error (difference to before: back to Reverse)
dC = zero(C)
res = autodiff(Reverse, g2, Active, Duplicated(C, dC))


```

# Full output

See https://gist.github.com/wisp3rwind/f27477fad8068b546a8f202d057cce16

**Comment by wsmoses** [comment]
Should now be fixed on main, please reopen if it persists.

**Comment by wisp3rwind** [comment]
Works now, thanks!
