### ISSUE TITLE
`cos`/`exp` on AMDGPU.jl

### ISSUE THREAD

**Issue by vchuravy** [EnzymeAD/Enzyme.jl#977]
These are currently failing due to missing adjoints for the OCL functions

https://github.com/EnzymeAD/Enzyme.jl/blob/0995d7ad6e4b1568e0857f66f006782241b0577a/test/amdgpu.jl#L41-L72

**Comment by wsmoses** [comment]
Resolved by https://github.com/EnzymeAD/Enzyme.jl/pull/1537
