### ISSUE TITLE
tape width issue using InlineStrings

### ISSUE THREAD

**Issue by motabbara** [EnzymeAD/Enzyme.jl#998]
Below fails since bar member of struct appears as i512. 

`
using Enzyme
using InlineStrings

struct Foo
    x::Float64
    bar::String63
end

function g(f::Foo)
    return f.x*5.0
end

function test()
    autodiff(Reverse, g, Active, Active(Foo(3.0, "a")))
end

test()`

**Comment by wsmoses** [comment]
Sure, go ahead and make a PR?
